-- Seed data: all sermons migrated from sermons-data.json
-- Run after 001_initial_schema.sql.

INSERT INTO sermons (book_slug, book_subtitle, passage, title, url, date) VALUES
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians', 'An Introduction to 1 Corinthians (Pt. 1)', 'https://soundcloud.com/user-440517750/an-introduction-to-first-corinthians', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians', 'An Introduction to 1 Corinthians (Pt. 2)', 'https://soundcloud.com/user-440517750/an-introduction-to-first-corinthians-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 1:1–9', 'Our Forever Faithful Father', 'https://soundcloud.com/user-440517750/our-forever-faithful-father', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 1:10–17', 'Our Identity in Christ Produces Unity in the Church', 'https://soundcloud.com/user-440517750/our-identity-in-christ-produces-unity-in-the-church', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 1:18–20', 'The Contrasting Message of the Cross (Pt. 1)', 'https://soundcloud.com/user-440517750/the-contrasting-message-of-the-cross', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 1:18–25', 'The Contrasting Message of the Cross (Pt. 2)', 'https://soundcloud.com/user-440517750/the-contrasting-message-of-the-cross-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 1:25–31', 'Christ is the Power and the Wisdom of God', 'https://soundcloud.com/user-440517750/christ-is-the-power-and-the-wisdom-of-god', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 1:29–31', 'The Boasting of God''s Elect', 'https://soundcloud.com/user-440517750/the-boasting-of-gods-elect', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 2:1–5', 'Our Crucified Christ: Is He Enough?', 'https://soundcloud.com/user-440517750/our-crucified-christ-is-he-enough', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 2:2', 'The All-Sufficient Cross of Christ', 'https://soundcloud.com/user-440517750/the-all-sufficient-cross-of-christ', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 2:6–9', 'Perfect Wisdom Prepared Before Time', 'https://soundcloud.com/user-440517750/perfect-wisdom-prepared-before-time', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 2:9–16', 'The Infinite Value of the Gift of the Spirit of God', 'https://soundcloud.com/user-440517750/the-infinite-value-of-the-gift-of-the-spirit-of-god', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 2:14–3:9', 'The Spirit-Filled, Christ-Centered Christian''s Works in God''s Field', 'https://soundcloud.com/user-440517750/the-spirit-filled-christ-centered-christians-works-in-gods-field', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 3:9–15', 'Great Is the Reward of Building God''s Way', 'https://soundcloud.com/user-440517750/great-is-the-reward-of-building-gods-way', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 3:16–23', 'A Temple of God or a Warehouse of Worldly Wisdom?', 'https://soundcloud.com/user-440517750/a-temple-of-god-or-a-warehouse-of-worldly-wisdom', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 4:1–5', 'A Servant-Leader Who Serves the True Judge', 'https://soundcloud.com/user-440517750/a-servant-leader-who-serves-the-true-judge', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 4:6–13', 'Will You Be Foolish to the World for the Glory of Christ?', 'https://soundcloud.com/user-440517750/will-you-be-foolish-to-the-world-for-the-glory-of-christ', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 4:14–21', 'The Appeal of a Loving Spiritual Father', 'https://soundcloud.com/user-440517750/the-appeal-of-a-loving-spiritual-father', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 5:1–5', 'Preserving the Gift of the Purity of Christ''s Church (Pt. 1)', 'https://soundcloud.com/user-440517750/preserving-the-gift-of-the-purity-of-christs-church', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 5:6–13', 'Preserving the Gift of the Purity of Christ''s Church (Pt. 2)', 'https://soundcloud.com/user-440517750/preserving-the-gift-of-the-purity-of-christs-church-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 6:1–11', 'God''s Kingdom Is Not of This World (Pt. 1)', 'https://soundcloud.com/user-440517750/gods-kingdom-is-not-of-this-world', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 6:9–11', 'God''s Kingdom Is Not of This World (Pt. 2)', 'https://soundcloud.com/user-440517750/gods-kingdom-is-not-of-this-world-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 6:12–20', 'The Redeemed Glorify Christ With Their Bodies Now and Forevermore', 'https://soundcloud.com/user-440517750/the-redeemed-glorify-christ-with-their-bodies-now-and-forevermore', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 7:1', 'Biblical Sexuality and An Introduction to 1 Corinthians 7', 'https://soundcloud.com/user-440517750/biblical-sexuality-and-an-introduction-to-1-corinthians-7', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 7:1–7', 'The Joy-Robbing Danger of Self-Righteousness', 'https://soundcloud.com/user-440517750/the-joy-robbing-danger-of-self-righteousness', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 7:6–11', 'God''s Design for Singleness and Marriage', 'https://soundcloud.com/user-440517750/gods-design-for-singleness-and-marriage', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 7:12–16', 'Unequally Yoked and Glorifying God', 'https://soundcloud.com/user-440517750/unequally-yoked-and-glorifying-god', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 7:17–24', 'Content in Our Calling', 'https://soundcloud.com/user-440517750/content-in-our-calling', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 7:25–31', 'A Life Fueled by the Mercy of God', 'https://soundcloud.com/user-440517750/a-life-fueled-by-the-mercy-of-god', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 7:32–40', 'Contentment Through Devotion to Christ', 'https://soundcloud.com/user-440517750/contentment-through-devotion-to-christ', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 8:1–3', 'A Divine Love that Creates Worshipful Knowledge', 'https://soundcloud.com/user-440517750/a-divine-love-that-creates-worshipful-knowledge', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 8:4–13', 'Christian Liberties and a Growing Love for Others (Pt. 1)', 'https://soundcloud.com/user-440517750/christian-liberties-and-a-growing-love-for-others', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 8:8–13', 'Christian Liberties and a Growing Love for Others (Pt. 2)', 'https://soundcloud.com/user-440517750/christian-liberties-and-a-growing-love-for-others-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 9:1–12', 'Enduring All Things for the Sake of the Gospel', 'https://soundcloud.com/user-440517750/enduring-all-things-for-the-sake-of-the-gospel', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 9:13–18', 'Christian Liberties and the Glory of God', 'https://soundcloud.com/user-440517750/christian-liberties-and-the-glory-of-god', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 9:19–27', 'The Self-Denying and Self-Controlling Nature of the Soul Winner (Pt. 1)', 'https://soundcloud.com/user-440517750/the-self-denying-and-self-controlling-nature-of-the-soul-winner-part-1', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 9:23–27', 'The Self-Denying and Self-Controlling Nature of the Soul Winner (Pt. 2)', 'https://soundcloud.com/user-440517750/the-self-denying-and-self-controlling-nature-of-the-soul-winner-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 10:1–10', 'The Grace of God That Warns (Pt. 1)', 'https://soundcloud.com/user-440517750/the-grace-of-god-that-warns', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 10:6–13', 'The Grace of God That Warns (Pt. 2)', 'https://soundcloud.com/user-440517750/the-grace-of-god-that-warns-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 10:11–13', 'The Grace of God That Warns (Pt. 3)', 'https://soundcloud.com/user-440517750/the-grace-of-god-that-warns-part-3', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 10:14–22', 'Unshared Glory', 'https://soundcloud.com/user-440517750/unshared-glory', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 10:23–11:1', 'The Pursuit of Glory (Pt. 1)', 'https://soundcloud.com/user-440517750/the-pursuit-of-glory', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 10:23–11:1', 'The Pursuit of Glory (Pt. 2)', 'https://soundcloud.com/user-440517750/the-pursuit-of-glory-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 11:2–16', 'The Glory of God and His Divine Order', 'https://soundcloud.com/user-440517750/the-glory-of-god-and-his-divine-order', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 11:17–22', 'The Perversion of Fellowship and the Lord''s Table', 'https://soundcloud.com/user-440517750/the-perversion-of-fellowship-and-the-lords-table', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 11:23–34', 'Worshipping Through Celebration and the Examination of the Lord''s Table', 'https://soundcloud.com/user-440517750/worshipping-through-celebration-and-examination-of-the-lords-table', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 11:23–26', 'The Christ-Centeredness of the Lord''s Table', 'https://youtu.be/RzKaZT3UX34?si=_PYEhlmLxaU98XYA', '2026-03-15'),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 11:27–34', 'When Christ is Not the Center of the Lord''s Table', 'https://youtu.be/xRmpB0pqskM?si=S8JxY1xqfInbGNQs', '2026-03-22'),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 12:1–3', 'A Spirit-Inspired and Christ-Centered Spirituality (Pt. 1)', 'https://soundcloud.com/user-440517750/a-spirit-inspired-and-christ-centered-spirituality', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 12:1–7', 'A Spirit-Inspired and Christ-Centered Spirituality (Pt. 2)', 'https://soundcloud.com/user-440517750/a-spirit-inspired-and-christ-centered-spirituality-pt-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 12:3–7', 'A Spirit-Inspired and Christ-Centered Spirituality (Pt. 3)', 'https://soundcloud.com/user-440517750/a-spirit-inspired-and-christ-centered-spirituality-pt-3', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 12:7–20', 'The Power of the Spirit to Unify Through Diversity (Pt. 1)', 'https://soundcloud.com/user-440517750/the-power-of-the-spirit-to-unify-through-diversity-pt-1', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 12:7–20', 'The Power of the Spirit to Unify Through Diversity (Pt. 2)', 'https://soundcloud.com/user-440517750/the-power-of-the-spirit-to-unify-through-diversity-part-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 12:21–31', 'Seeking a More Excellent Way with Our Spiritual Gifts', 'https://soundcloud.com/user-440517750/seeking-a-more-excellent-way-with-our-spiritual-gifts', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 13', 'When the Church Settles for Less', 'https://soundcloud.com/user-440517750/when-the-church-settles-for-less', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 13', 'The Love of Christ', 'https://soundcloud.com/user-440517750/the-love-of-christ', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 13:4–13', 'The Love of Christ and the Coming of the Perfect (Pt. 1)', 'https://soundcloud.com/user-440517750/the-love-of-christ-and-the-coming-of-the-perfect', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 13:8–13', 'The Love of Christ and the Coming of the Perfect (Pt. 1)', 'https://soundcloud.com/user-440517750/the-love-of-christ-and-the-coming-of-the-perfect-pt-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 14:1–19', 'The Pursuit of Love and the Building Up of the Church', 'https://soundcloud.com/user-440517750/the-pursuit-of-love-and-the-building-up-of-the-church', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 14:12–25', 'Pagan Prayer Language and a Sign of Judgment', 'https://soundcloud.com/user-440517750/pagan-prayer-language-and-a-sign-of-judgment', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 14:26–40', 'Let All Things Be Done for Edification and for the Glory of Christ (Pt. 1)', 'https://soundcloud.com/user-440517750/let-all-things-be-done-for-edification-and-for-the-glory-of-christ', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 14:33–40', 'Let All Things Be Done for Edification and for the Glory of Christ (Pt. 2)', 'https://soundcloud.com/user-440517750/let-all-things-be-done-for-edification-and-for-the-glory-of-christ-pt-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:1–11', 'The Resurrection and Our Worship', 'https://soundcloud.com/user-440517750/the-resurrection-and-our-worship', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:1–11', 'The Life-Giving Resurrection', 'https://soundcloud.com/user-440517750/the-life-giving-resurrection', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:12–20', 'If Christ Is Not Bodily Resurrected (Pt. 1)', 'https://soundcloud.com/user-440517750/if-christ-is-not-bodily-resurrected', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:16–22', 'If Christ Is Not Bodily Resurrected (Pt. 2)', 'https://soundcloud.com/user-440517750/if-christ-is-not-bodily-resurrected-pt-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:20–28', 'The Divine Results of Christ''s Bodily Resurrection', 'https://soundcloud.com/user-440517750/the-divine-results-of-christs-bodily-resurrection', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:29–34', 'No Resurrection, No Morals', 'https://soundcloud.com/user-440517750/no-resurrection-no-morals', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:35–49', 'Rags to Riches in the Glory of Christ', 'https://soundcloud.com/user-440517750/rags-to-riches-in-the-glory-of-christ', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:50–57', 'Oh, Victory in Jesus, My Savior Forever', 'https://soundcloud.com/user-440517750/oh-victory-in-jesus-my-savior-forever', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:58', 'Abounding in the Work of the Lord (Pt. 1)', 'https://soundcloud.com/user-440517750/abounding-in-the-work-of-the-lord-pt-1', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:58', 'Abounding in the Work of the Lord (Pt. 2)', 'https://soundcloud.com/user-440517750/abounding-in-the-work-of-the-lord-pt-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:58', 'Abounding in the Work of the Lord (Pt. 3)', 'https://soundcloud.com/user-440517750/abounding-in-the-work-of-the-lord-pt-3', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:58', 'Abounding in the Work of the Lord (Pt. 4)', 'https://soundcloud.com/user-440517750/abounding-in-the-work-of-the-lord-pt-4', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 15:58', 'Abounding in the Work of the Lord (Pt. 5)', 'https://soundcloud.com/user-440517750/abounding-in-the-work-of-the-lord-pt-5', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 16:1–9', 'Generous Giving and Joining in the Work of Our Lord', 'https://soundcloud.com/user-440517750/generous-giving-and-joining-in-the-work-of-our-lord', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 16:10–14', 'The Godly Characteristics of the Lord''s Workers (Pt. 1)', 'https://soundcloud.com/user-440517750/the-godly-characteristics-of-the-lords-workers', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 16:13–14', 'The Godly Characteristics of the Lord''s Workers (Pt. 2)', 'https://soundcloud.com/user-440517750/the-godly-characteristics-of-the-lords-workers-pt-2', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 16:13–16', 'The Godly Characteristics of the Lord''s Workers (Pt. 3)', 'https://soundcloud.com/user-440517750/the-godly-characteristics-of-the-lords-workers-pt-3', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 16:13–16', 'The Godly Characteristics of the Lord’s Workers (Pt. 3)', 'https://youtu.be/kX301GMw1Yg?si=VJ10WioB91g20lZh&t=2461', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 16:13–14', 'Five Priorities of a Biblical Father', 'https://youtu.be/s28YdCKzXr8?si=VDQmuVwnVHmnk8lL', NULL),
  ('1-corinthians', 'Christ-Centered Living in a Sinful World', '1 Corinthians 16:15–24', 'Love Christ, Love His Word, and Love His People', 'https://youtu.be/9of6gbDpoCc?si=st_FeOR6AOjKomoY&t=2462', NULL),
  ('1-john', NULL, '1 John 4:9–10', 'Christmas: A Display of God''s Divine Love', 'https://soundcloud.com/user-440517750/christmas-a-display-of-gods-divine-love', NULL),
  ('1-john', NULL, '1 John 4:11–13', 'Love Without Limits (Pt. 1)', 'https://soundcloud.com/user-440517750/love-without-limits-2022-challenge-to-rcc-part-1', NULL),
  ('1-john', NULL, '1 John 4:11–13', 'Love Without Limits (Pt. 2)', 'https://soundcloud.com/user-440517750/love-without-limits-2022-challenge-to-rcc-part-2', NULL),
  ('1-peter', NULL, '1 Peter 1:1–8', 'Our Motivation for Missions', 'https://youtu.be/yZeDOTAxZeQ?si=AfCBGYxu7b7S5fWh', NULL),
  ('1-peter', NULL, '1 Peter 1:12', 'The Angels and the Resurrection', 'https://soundcloud.com/user-440517750/the-angels-and-the-resurrection', NULL),
  ('1-peter', NULL, '1 Peter 1:17–21', 'The Resurrected Christ and Our Faith and Hope in God', 'https://soundcloud.com/user-440517750/the-resurrected-christ-and-our-faith-and-hope-in-god', NULL),
  ('1-peter', NULL, '1 Peter 2:11–12', 'There are Aliens on the Earth!', 'https://soundcloud.com/user-440517750/there-are-aliens-on-the-earth', NULL),
  ('1-peter', NULL, '1 Peter 2:21–25', 'Suffering and the Glory of Christ', 'https://soundcloud.com/user-440517750/suffering-and-the-glory-of-christ', NULL),
  ('1-peter', NULL, '1 Peter 4:12–5:4', 'The Great Shepherd and His Precious Flock', 'https://soundcloud.com/user-440517750/the-great-shepherd-and-his-precious-flock', NULL),
  ('1-peter', NULL, '1 Peter 5:1–4', 'Shepherding the Flock of God', 'https://soundcloud.com/user-440517750/shepherding-the-flock-of-god', NULL),
  ('1-peter', NULL, '1 Peter 5:5–9', 'Humble Submission and a Faith that Stands Firm', 'https://soundcloud.com/user-440517750/humble-submission-and-a-faith-that-stands-firm', NULL),
  ('1-samuel', NULL, '1 Samuel 1', 'Women Who Find Favor in God''s Sight', 'https://soundcloud.com/user-440517750/051020a', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 1:1', 'An Introduction of 1 Thessalonians', 'https://youtu.be/fOmf-bqHfzE?si=UouFToo7k5ZUYZMg&t=1981', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 1:1', 'A Shepherd''s Greeting', 'https://youtu.be/fBN8kokipXU?si=eCzWIsCXp1PXasT7&t=2099', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 1:1–2:2', 'The Biblical Example of the Thessalonica Church', 'https://youtu.be/GcYAJqjeSrw', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 1:2–4', 'Prayers of Thanksgiving for Fruitfulness', 'https://youtu.be/YzzJwbjLV0Y?si=wRTtVwcNb2pvhKiN&t=1781', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 1:5–10', 'God''s Word-Saturated and Spirit-Inspired Missional Plan', 'https://youtu.be/ylCdUqTvdfQ?si=rbAyBxgX9FyrnoWf', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 2:1–12', 'A Biblical Leader’s Love for the Glory of Christ and His Church', 'https://youtu.be/basjF5o8fOA', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 2:7–12', 'The Nature of Those Captured by the Glory of Christ', 'https://youtu.be/ZteXruYna2E', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 2:13–20', 'The True Church is Faithful to God''s Word, Discipleship, and Each Other', 'https://www.youtube.com/watch?v=AOit16VWw3g', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 3:1-6', 'The Gospel That Produces Faith, Love, Joy, and a Kindred Spirit', 'https://youtu.be/hb5B3JX_lXM', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 3:6-13', 'A Church Worth Suffering and Praying For', 'https://youtu.be/eagq-psJxpM', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 4:1–2', 'Living Excellent In Christ (Pt. 1)', 'https://youtu.be/Tnrj0KyqvnU', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 4:1–2', 'Living Excellent In Christ (Pt. 2)', 'https://youtu.be/7aT0oHSmpFc?si=77Sh9xbwxxW8r00Z', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 4:3–8', 'Keeping Our Behavior Excellent for God’s Glory and Our Good', 'https://youtu.be/CBt5OzsshnQ', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 4:9–12', 'A Love From God That Excels Still More', 'https://www.youtube.com/watch?v=ZFRQQPhK1hU', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 4:13–18', 'The Comfort of the Coming Christ', 'https://www.youtube.com/watch?v=gg_mYwXWKFk', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 5:1–3', 'The Children of God and the Day of the Lord (Pt. 1)', 'https://youtu.be/l5_afaWirgA', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 5:3–11', 'The Children of God and the Day of the Lord (Pt. 2)', 'https://youtu.be/rQCWpkCE4e8', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 5:12–13', 'God''s Shepherds and God''s Sheep (Pt. 1)', 'https://soundcloud.com/user-440517750/gods-shepherds-and-gods-sheep', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 5:12–13', 'God''s Shepherds and God''s Sheep (Pt. 2)', 'https://soundcloud.com/user-440517750/gods-shepherds-and-gods-sheep-part-2', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 5:12–15', 'The Church That Lives In Harmony With Christ and One Another', 'https://youtu.be/M006bZtsXBA', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 5:16-18', 'The Consistent Rejoicing, Prayerful, and Thankful Life of a Christian', 'https://youtu.be/Im1gMaf0K1s', NULL),
  ('1-thessalonians', 'A Shepherd and His Flock', '1 Thessalonians 5:19–28', 'The Spirit of God and the Church''s Responsibilities', 'https://youtu.be/PImcLe4WeHY', NULL),
  ('1-timothy', NULL, '1 Timothy 1:12–17', 'Lord, Help Me to Stay in the Good Fight', 'https://soundcloud.com/user-440517750/lord-help-me-to-stay-in-the-good-fight', NULL),
  ('1-timothy', NULL, '1 Timothy 3:1–7', 'God''s Design for the Leadership of His Church, Pt. 1', 'https://youtu.be/Bg9LDBYyIN8?si=xaxrxXwOr8x_P77M', NULL),
  ('1-timothy', NULL, '1 Timothy 3:1–7', 'God''s Design for the Leadership of His Church, Pt. 2', 'https://youtu.be/nlqSWWbkupo?si=AnflmnaKNwY2h72z', NULL),
  ('1-timothy', NULL, '1 Timothy 3:8–15', 'The Ministers of Mercy', 'https://soundcloud.com/user-440517750/the-ministers-of-mercy', NULL),
  ('1-timothy', NULL, '1 Timothy 4:6–11', 'The Importance of Feeding Our Souls on Sound Doctrine', 'https://youtu.be/WFDXYrN0R0I?si=2GLNcVIi-c-meOjr', NULL),
  ('2-corinthians', NULL, '2 Corinthians 5:14–17', 'The Unfathomable Love of God and our Uncompromising Response', 'https://youtu.be/cLaV59S-3rs', NULL),
  ('2-corinthians', NULL, '2 Corinthians 8:1–9', 'Christ-Centered, Generous, and Gracious Giving', 'https://soundcloud.com/user-440517750/christ-centered-generous-and-gracious-giving', NULL),
  ('2-corinthians', NULL, '2 Corinthians 9:6–15', 'Indescribable Giving', 'https://soundcloud.com/user-440517750/indescribable-giving', NULL),
  ('2-peter', NULL, '2 Peter 1:1–11', 'Disciplining Ourselves for the Glory of Christ', 'https://soundcloud.com/user-440517750/disciplining-ourselves-for-the-glory-of-christ', NULL),
  ('2-peter', NULL, '2 Peter 1:1–11', 'The Gracious Gift of True Christianity', 'https://youtu.be/3jwTCNvcHaQ?si=dfIDWpzX4Cl7smNi', NULL),
  ('2-peter', NULL, '2 Peter 1:1–12', 'The Responsibility of the Individual Members of the Body', 'https://youtu.be/3xQsMXHWaeY?si=GU-jLVjddg2kEqre', NULL),
  ('2-peter', NULL, '2 Peter 1:16–21', 'Loving the Sufficiency of the Word of God (Pt. 1)', 'https://youtu.be/Y7yR3-i4HA0?si=70ZfOroJp75DHXyC&t=2376', NULL),
  ('2-peter', NULL, '2 Peter 1:16–21', 'Loving the Sufficiency of the Word of God (Pt. 2)', 'https://youtu.be/Ewc1IjaGT9c?si=l0nPfkyVubyNOfzg&t=1994', NULL),
  ('2-peter', NULL, '2 Peter 1:16–21', 'A Pastor''s Responsibility to the Sufficiency of the Word of God', 'https://youtu.be/RRMe1bWyFvU?si=g1Nc5URI5mgTwMqs', NULL),
  ('2-timothy', NULL, '2 Timothy 3:10–17', 'The Christian Captured by the Word', 'https://youtu.be/hgTWj7-ADrM?si=vZCoH2I9p2ODyMqi&t=1908', NULL),
  ('2-timothy', NULL, '2 Timothy 3:14–17', 'The Precious Gift of God''s Word', 'https://youtu.be/jF0oeZbWxPw', NULL),
  ('acts', NULL, 'Acts 2:22–24', 'The Empowering Affects of the Resurrection', 'https://soundcloud.com/user-440517750/the-empowering-affects-of-the-resurrection', NULL),
  ('acts', NULL, 'Acts 14–16', 'Missions God''s Way', 'https://youtu.be/63ni5BsiRMc?si=v4kypfRZihlIKoSo', NULL),
  ('acts', NULL, 'Acts 14:19–16:40', 'The Nature of a True Missionary', 'https://youtu.be/tSotUUwOzss', NULL),
  ('acts', NULL, 'Acts 20:17–28', 'The Elder Who Teaches, Shepherds, and Evangelizes', 'https://youtu.be/3lKFjjEe-8M', NULL),
  ('colossians', NULL, 'Colossians 1:13–20', 'Our Rescuer is Also the Head of the Church', 'https://youtu.be/_laAa3IYUNw?si=7etryMMLzqQkQraP', NULL),
  ('colossians', NULL, 'Colossians 1:16–18', 'Christ, the Head of the Church, is Preeminent Over All Things', 'https://youtu.be/qZvhMg005gg?si=FpvqaHVLYI0DRdGp', NULL),
  ('colossians', NULL, 'Colossians 2:9–15', 'The Assurance of True Salvation', 'https://youtu.be/Pll3M5PivRw?si=lK7a_4jR0vs7QFnq', NULL),
  ('colossians', NULL, 'Colossians 3:1–11', 'Eternity-Minded Christians Will Seek to Kill Sin', 'https://soundcloud.com/user-440517750/eternity-minded-christians-will-seek-to-kill-sin', NULL),
  ('colossians', NULL, 'Colossians 3:15–25', 'Developing a Culture of Gratitude', 'https://soundcloud.com/user-440517750/developing-a-culture-of-gratitude', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 1:1–5', 'An Introduction to Deuteronomy', 'https://youtu.be/VbSpSiSmZCE?si=F6CNnwJnTJLLqlwu&t=1035', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 1', 'The Circular Nature of Sin', 'https://youtu.be/X20tN41euI8?si=UT_uqqpPzH6BNUmM&t=1484', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 2–3', 'God is Imbedded in History', 'https://youtu.be/DUmjr_j1Jyw?si=euEoB7Cp2fEQjSkx&t=1009', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 4', 'The Law and the Gospel (Pt. 1)', 'https://youtu.be/LasbX6k1_C8?si=UeOSOs070ia7usou&t=1434', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 4', 'The Law and the Gospel (Pt. 2)', 'https://youtu.be/N1yb6RDdT3g?si=scVc--ibWu6_dQUt&t=2524', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 5:1–15', 'The Authority of God''s Word and the Motivation to Obey It (Pt. 2)', 'https://youtu.be/cv8ewOpOIp8?si=a2i7UfQMdBrSgfj8', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 6', 'The Greatest Command', 'https://youtu.be/XxtfDZES1Vc?si=2tu_jT5uHvO57ArT', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 7', 'Holy War Through A Holy Savior', 'https://youtu.be/x3f_vApad7o?si=ColqqqOGLkLnG2XY', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 8', 'Remembrance That Leads to Worship', 'https://youtu.be/CG7oYzLDdso?si=JxezP6jcW5wxy2ER', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 9', 'Our Sin and the Grace and Glory of God', 'https://www.youtube.com/watch?v=OlRJJ3ORJJo', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 10', 'Is Yahweh Worthy of Our Praise?', 'https://www.youtube.com/watch?v=H07myJLar0k', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 11', 'Love-Driven Obedience', 'https://www.youtube.com/watch?v=BrkHe85cOPE', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 12', 'Love-Driven Life', 'https://youtu.be/D-5WpZvFljU', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 13', 'A Warning of the Eroding of Truth', 'https://youtu.be/QxutehTtClM', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 14', 'The Holiness of God Lived Out in Daily Life', 'https://youtu.be/yep5PljtgQ8', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 15', 'The Year of Grace', 'https://youtu.be/CBpJ9FHZ0d0', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 16', 'Celebrating the Redemption, Provision, and Justice of God', 'https://youtu.be/VSVEWaLTM8U', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 17', 'The Catastrophic Differences Between a High or Low View of God', 'https://youtu.be/EwrhcPc0hFM', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 18', 'The Great Prophet, Priest, and King: The Lord Jesus Christ', 'https://youtu.be/F4xoSd5zBw4', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 19', 'The Justice of God and Common Grace for His People', 'https://youtu.be/Gg5cCNCw1BY', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 20', 'Trusting and Obeying the Commander and Chief of Our Souls', 'https://youtu.be/e1dCse41Ajg', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 21', 'God''s Divine Bill of Rights for the Sanctity of Life and Death', 'https://youtu.be/q9S1iXcUvnU', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 22:1–12', 'The Righteousness of God in Daily Living', 'https://youtu.be/kgwBcCwRWCE', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 22:13–30', 'The Righteousness of God and the Sanctity of Marriage and Purity', 'https://youtu.be/kRXcxp615_0', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 23', 'Reflecting Our Holy God', 'https://youtu.be/FeFzTrICjk8', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 24', 'The Motivation of Our Loving God', 'https://youtu.be/2e8VhpZ1hwg', NULL),
  ('deuteronomy', NULL, 'Deuteronomy 25', 'Laws Reflecting the Mercy of God', 'https://youtu.be/WMRBD4QLVzg?si=cCZFIO4BaA7ZQEls', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 1', 'Introduction to Ecclesiastes', 'https://soundcloud.com/user-440517750/ecclesiastes-part-1-introduction', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 1:2–11', 'The Brevity of Life', 'https://soundcloud.com/user-440517750/ecclesiastes-the-brevity-of-life', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 1:12–18', 'The Meaning of Life Without Christ', 'https://soundcloud.com/user-440517750/ecclesiastes-the-meaning-of-life-without-christ', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 2:1–11', 'Testing Pleasure Apart from God', 'https://soundcloud.com/user-440517750/testing-pleasure-apart-from-god', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 2:12–17', 'Are You Looking Under the Sun or to the Son?', 'https://soundcloud.com/user-440517750/are-you-looking-under-the-sun-or-to-the-son', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 2:17–26', 'Working for Jesus', 'https://soundcloud.com/user-440517750/working-for-jesus', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 3:1–11', 'The Completeness of God', 'https://soundcloud.com/user-440517750/the-completeness-of-god', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 3:9–15', 'God Will Make All Things Beautiful', 'https://soundcloud.com/user-440517750/god-will-make-all-things-beautiful', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 3:16–4:3', 'From Dust to Dust', 'https://soundcloud.com/user-440517750/from-dust-to-dust', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 4:4–16', 'The Joy of Obedience', 'https://soundcloud.com/user-440517750/the-joy-of-obedience', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 5:1–7', 'Enter His Courts with Praise (Pt. 1)', 'https://soundcloud.com/user-440517750/enter-his-courts-with-praise', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 5:1–7', 'Enter His Courts with Praise (Pt. 2)', 'https://soundcloud.com/user-440517750/enter-his-courts-with-praise', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 5:8–20', 'Satisfied in God', 'https://soundcloud.com/user-440517750/satisfied-in-god', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 6', 'Life Without God', 'https://soundcloud.com/user-440517750/life-without-god', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 7:1–12', 'Living in the Light of Eternity', 'https://soundcloud.com/user-440517750/living-in-the-light-of-eternity', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 7:13–18', 'Drawing Straight Lines with Crooked Sticks', 'https://soundcloud.com/user-440517750/drawing-straight-lines-with-crooked-stick', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 7:19–29', 'The Search for Wisdom', 'https://soundcloud.com/user-440517750/the-search-for-wisdom', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 8:10–15', 'The Joy and Justice of the Lord', 'https://soundcloud.com/user-440517750/the-joy-and-justice-of-the-lord', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 8:16–9:6', 'Limited Happiness With No Future Hope', 'https://soundcloud.com/user-440517750/limited-happiness-with-no-future-hope', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 9:7–10', 'Enjoyment Is Approved by God', 'https://soundcloud.com/user-440517750/enjoyment-is-approved-by-god', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 9:11–18', 'The Great Gap Between God and Man', 'https://soundcloud.com/user-440517750/the-great-gap-between-god-and-man', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 10:1–11', 'Sweet Wisdom and the Stench of Foolishness', 'https://soundcloud.com/user-440517750/sweet-wisdom-and-the-stench-of-foolishness', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 10:12–20', 'Fools Rush In', 'https://soundcloud.com/user-440517750/fools-rush-in', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 11:1–6', 'Faith-Driven Courage', 'https://soundcloud.com/user-440517750/faith-driven-courage', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 11:7–10', 'Rejoice in this Life Under the Sun', 'https://soundcloud.com/user-440517750/rejoice-in-this-life-under-the-sun', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 12:1–7', 'A God-Centered Call of Remembrance', 'https://soundcloud.com/user-440517750/a-god-centered-call-of-remembrance', NULL),
  ('ecclesiastes', 'The Emptiness of Life & Eternity Apart from Christ', 'Ecclesiastes 12:8–14', 'The Shepherd We Worship and Serve', 'https://soundcloud.com/user-440517750/the-shepherd-we-worship-and-serve', NULL),
  ('ephesians', NULL, 'Ephesians 1:3–4', 'The Doctrine of Love', 'https://soundcloud.com/user-440517750/the-doctrine-of-love', NULL),
  ('ephesians', NULL, 'Ephesians 2:1–3', 'Dead Men Walking: The Nature of Depravity (Pt. 1)', 'https://soundcloud.com/user-440517750/dead-men-walking-the-nature-of-depravity', NULL),
  ('ephesians', NULL, 'Ephesians 2:1–3', 'Dead Men Walking: The Nature of Depravity (Pt. 2)', 'https://soundcloud.com/user-440517750/dead-men-walking-the-nature-of-depravity-part-2', NULL),
  ('ephesians', NULL, 'Ephesians 2:1–10', 'Dead Men Walking: Made Alive in Christ', 'https://youtu.be/7HqqeQOXWuQ2', NULL),
  ('ephesians', NULL, 'Ephesians 3:14–21', 'Knowing and Loving Our Unfathomable Father', 'https://soundcloud.com/user-440517750/knowing-and-loving-our-unfathomable-father', NULL),
  ('ephesians', NULL, 'Ephesians 4:6', 'A Father''s Godly Influence', 'https://soundcloud.com/user-440517750/a-fathers-godly-influence', NULL),
  ('ephesians', NULL, 'Ephesians 4:14–16', 'What Is Your Role in Christ''s Church?', 'https://youtu.be/xc4Hl-qT3jE?si=fKvORD3FyLzCHL93', '2026-06-14'),
  ('ephesians', NULL, 'Ephesians 6:10–20', 'Embattled in Spiritual Warfare but Invincible in Christ (Pt. 1)', 'https://youtu.be/ZlYI6tYtEos', NULL),
  ('ephesians', NULL, 'Ephesians 6:13–20', 'Embattled in Spiritual Warfare but Invincible in Christ (Pt. 2)', 'https://youtu.be/EwmcGRMvZqY', NULL),
  ('exodus', NULL, 'Exodus 1', 'Egypt''s War Against God', 'https://soundcloud.com/user-440517750/egypts-war-against-god', NULL),
  ('exodus', NULL, 'Exodus 2', 'The Making of a New Godly Leader', 'https://soundcloud.com/user-440517750/the-making-of-a-new-godly-leader', NULL),
  ('exodus', NULL, 'Exodus 3', 'The Great ''I Am'' God Calls, Cares, and Commissions (Pt. 1)', 'https://soundcloud.com/user-440517750/the-great-i-am-god-calls-cares-and-commissions', NULL),
  ('exodus', NULL, 'Exodus 3', 'The Great ''I Am'' God Calls, Cares, and Commissions (Pt. 2)', 'https://soundcloud.com/user-440517750/the-great-i-am-god-calls-cares-and-commissions-pt-2', NULL),
  ('exodus', NULL, 'Exodus 4:1–17', 'Here Am I Lord, No Wait, What?', 'https://soundcloud.com/user-440517750/here-am-i-lord-no-wait-what', NULL),
  ('exodus', NULL, 'Exodus 4:18–31', 'The Faithfulness of God is Our Only Hope for Peace', 'https://soundcloud.com/user-440517750/the-faithfulness-of-god-is-our-only-hope-for-peace', NULL),
  ('exodus', NULL, 'Exodus 5', 'When God Does Not Perform the Way You Want Him To', 'https://soundcloud.com/user-440517750/when-god-does-not-perform-the-way-you-want-him-to', NULL),
  ('exodus', NULL, 'Exodus 6', 'God''s Steadfast Grace', 'https://soundcloud.com/user-440517750/gods-steadfast-grace', NULL),
  ('exodus', NULL, 'Exodus 7:1–13', 'The God of Involuntary Freedom (Pt. 1)', 'https://soundcloud.com/user-440517750/the-god-of-involuntary-freedom', NULL),
  ('exodus', NULL, 'Exodus 7:8–25', 'The God of Involuntary Freedom (Pt. 2)', 'https://soundcloud.com/user-440517750/the-god-of-involuntary-freedom-part-2', NULL),
  ('exodus', NULL, 'Exodus 8', 'A God Like None Other', 'https://soundcloud.com/user-440517750/a-god-like-none-other', NULL),
  ('exodus', NULL, 'Exodus 9:1–7', 'Dead Gods and the Environment', 'https://soundcloud.com/user-440517750/dead-gods-and-the-environment', NULL),
  ('exodus', NULL, 'Exodus 9:8–25', 'The Judgment of God Reveals the Depravity of Man', 'https://soundcloud.com/user-440517750/the-judgment-of-god-reveals-the-depravity-of-man', NULL),
  ('exodus', NULL, 'Exodus 10', 'A Calamity-Creating God', 'https://soundcloud.com/user-440517750/a-calamity-creating-god', NULL),
  ('exodus', NULL, 'Exodus 11', 'The Judgments and Wonders of God', 'https://soundcloud.com/user-440517750/the-judgments-and-wonders-of-god', NULL),
  ('exodus', NULL, 'Exodus 12', 'The Lamb That Can Beat Death!', 'https://soundcloud.com/user-440517750/the-lamb-that-can-beat-death', NULL),
  ('exodus', NULL, 'Exodus 12:14–51', 'God''s Promises: Aroma of Life or Death?', 'https://soundcloud.com/user-440517750/gods-promises-aroma-of-life-or-death', NULL),
  ('exodus', NULL, 'Exodus 13', 'Remembering Our Great God and Savior in a Post-Slavery World', 'https://soundcloud.com/user-440517750/remembering-our-great-god-and-savior-in-a-post-slavery-world', NULL),
  ('exodus', NULL, 'Exodus 14', 'Fear Not, God is Fighting for You', 'https://soundcloud.com/user-440517750/fear-not-god-is-fighting-for-you', NULL),
  ('exodus', NULL, 'Exodus 15:1–16:7', 'Praising and Grumbling: A Serious Heart Condition', 'https://soundcloud.com/user-440517750/praising-and-grumbling-a-serious-heart-condition', NULL),
  ('exodus', NULL, 'Exodus 16:8–36', 'The Struggles of Submission to Our Gracious God', 'https://soundcloud.com/user-440517750/the-struggles-of-submission-to-our-gracious-god', NULL),
  ('exodus', NULL, 'Exodus 17', 'Trust and Obey for There Is No Other Way', 'https://soundcloud.com/user-440517750/trust-and-obey-for-there-is-no-other-way', NULL),
  ('exodus', NULL, 'Exodus 18', 'Humility, Wisdom, and the Oversight of God''s People', 'https://soundcloud.com/user-440517750/humility-wisdom-and-the-oversight-of-gods-people', NULL),
  ('exodus', NULL, 'Exodus 19', 'Behold Your King!', 'https://soundcloud.com/user-440517750/behold-your-king', NULL),
  ('exodus', NULL, 'Exodus 20:1–6', 'Fellowship with Yahweh (Pt. 1)', 'https://soundcloud.com/user-440517750/fellowship-with-yahweh', NULL),
  ('exodus', NULL, 'Exodus 20:4–11', 'Fellowship with Yahweh (Pt. 2)', 'https://soundcloud.com/user-440517750/fellowship-with-yahweh-part-2', NULL),
  ('exodus', NULL, 'Exodus 20:7–12', 'Fellowship with Yahweh (Pt. 3)', 'https://soundcloud.com/user-440517750/fellowship-with-yahweh-part-3', NULL),
  ('exodus', NULL, 'Exodus 20:12–14', 'Fellowship with Yahweh (Pt. 4)', 'https://soundcloud.com/user-440517750/fellowship-with-yahweh-pt-4', NULL),
  ('exodus', NULL, 'Exodus 20:14–16', 'Fellowship with Yahweh (Pt. 5)', 'https://soundcloud.com/user-440517750/fellowship-with-yahweh-pt-5', NULL),
  ('exodus', NULL, 'Exodus 20:15–17', 'Fellowship with Yahweh (Pt. 6)', 'https://soundcloud.com/user-440517750/fellowship-with-yahweh-pt-6', NULL),
  ('exodus', NULL, 'Exodus 20:18–26', 'Worshipping the True Almighty God', 'https://soundcloud.com/user-440517750/worshipping-the-true-almighty-god', NULL),
  ('exodus', NULL, 'Exodus 21', 'Life Under the Sun in Israel', 'https://soundcloud.com/user-440517750/life-under-the-sun-in-israel', NULL),
  ('exodus', NULL, 'Exodus 22–23', 'The Holy God and Those Who Follow Him', 'https://soundcloud.com/user-440517750/the-holy-god-and-those-who-follow-him', NULL),
  ('exodus', NULL, 'Exodus 24', 'The Old Covenant That Points to the New', 'https://soundcloud.com/user-440517750/the-old-covenant-that-points-to-the-new', NULL),
  ('exodus', NULL, 'Exodus 25–26', 'Preparing for the Presence of God (Pt. 1)', 'https://soundcloud.com/user-440517750/preparing-for-the-presence-of-god', NULL),
  ('exodus', NULL, 'Exodus 26–28', 'Preparing for the Presence of God (Pt. 2)', 'https://soundcloud.com/user-440517750/preparing-for-the-presence-of-god-part-2', NULL),
  ('exodus', NULL, 'Exodus 28–31', 'Preparing for the Presence of God (Pt. 3)', 'https://soundcloud.com/user-440517750/preparing-for-the-presence-of-god-part-3', NULL),
  ('exodus', NULL, 'Exodus 32:1–24', 'There Is No Life Without the Mediator (Pt. 1)', 'https://soundcloud.com/user-440517750/there-is-no-life-without-the-mediator', NULL),
  ('exodus', NULL, 'Exodus 32:11–35', 'There Is No Life Without the Mediator (Pt. 2)', 'https://soundcloud.com/user-440517750/there-is-no-life-without-the-mediator-part-2', NULL),
  ('exodus', NULL, 'Exodus 33', 'Show Me Your Glory! (Pt. 1)', 'https://soundcloud.com/user-440517750/show-me-your-glory', NULL),
  ('exodus', NULL, 'Exodus 34:1–7', 'Show Me Your Glory! (Pt. 2)', 'https://soundcloud.com/user-440517750/show-me-your-glory-part-2', NULL),
  ('exodus', NULL, 'Exodus 34:6–9', 'Show Me Your Glory! (Pt. 3)', 'https://soundcloud.com/user-440517750/show-me-your-glory-part-3', NULL),
  ('exodus', NULL, 'Exodus 34:8–35', 'Show Me Your Glory! (Pt. 4)', 'https://soundcloud.com/user-440517750/show-me-your-glory-part-4', NULL),
  ('exodus', NULL, 'Exodus 34:17–35', 'Show Me Your Glory! (Pt. 5)', 'https://soundcloud.com/user-440517750/show-me-your-glory-part-5', NULL),
  ('exodus', NULL, 'Exodus 35–39', 'A Tabernacle Without a Chair', 'https://soundcloud.com/user-440517750/a-tabernacle-without-a-chair', NULL),
  ('exodus', NULL, 'Exodus 40', 'An Earthly Tabernacle Ready for Its Heavenly King', 'https://soundcloud.com/user-440517750/an-earthly-tabernacle-ready-for-its-heavenly-king', NULL),
  ('galatians', NULL, 'Galatians 4:1–7', 'Christmas and God''s Forever Family', 'https://soundcloud.com/user-440517750/christmas-and-gods-forever-family', NULL),
  ('genesis', NULL, 'Genesis 1:1', 'Our Eternal God', 'https://soundcloud.com/user-440517750/our-eternal-god', NULL),
  ('genesis', NULL, 'Genesis 1:1–2', 'The Power and Wisdom to Create', 'https://soundcloud.com/user-440517750/111517p', NULL),
  ('genesis', NULL, 'Genesis 1:1–2', 'God and His Creation', 'https://soundcloud.com/user-440517750/god-and-his-creation', NULL),
  ('genesis', NULL, 'Genesis 1:1–13', 'Creation and Worship (Pt. 1)', 'https://soundcloud.com/user-440517750/creation-and-worship', NULL),
  ('genesis', NULL, 'Genesis 1:14–23', 'Creation and Worship (Pt. 2)', 'https://soundcloud.com/user-440517750/creation-and-worship-part-2', NULL),
  ('genesis', NULL, 'Genesis 1:24–31', 'The Climax of God''s Perfect Creation (Pt. 1)', 'https://soundcloud.com/user-440517750/013118p', NULL),
  ('genesis', NULL, 'Genesis 1:24–31', 'The Climax of God''s Perfect Creation (Pt. 2)', 'https://soundcloud.com/user-440517750/the-climax-of-gods-perfect-creation-part-2', NULL),
  ('genesis', NULL, 'Genesis 1:26–31', 'Masculinity That Reflects Our Creator', 'https://youtu.be/eQFBY_7ZxAQ?si=rirRjK60blw4RwSU', NULL),
  ('genesis', NULL, 'Genesis 2', 'The Beauty of God and His Sinless Creation', 'https://soundcloud.com/user-440517750/the-beauty-of-god-and-his-sinless-creation', NULL),
  ('genesis', NULL, 'Genesis 3:1–6', 'Satan the Deceiver', 'https://soundcloud.com/user-440517750/satan-the-deceiver', NULL),
  ('genesis', NULL, 'Genesis 3:6–13', 'The Sin of Adam and the Separation from God', 'https://soundcloud.com/user-440517750/the-sin-of-adam-and-the-separation-from-god', NULL),
  ('genesis', NULL, 'Genesis 3:14–24', 'The Curse of Sin and the Graciousness of God (Pt. 1)', 'https://soundcloud.com/user-440517750/the-curse-of-sin-and-the-graciousness-of-god', NULL),
  ('genesis', NULL, 'Genesis 3:21–4:2', 'The Curse of Sin and the Graciousness of God (Pt. 2)', 'https://soundcloud.com/user-440517750/the-curse-of-sin-and-the-graciousness-of-god-part-2', NULL),
  ('genesis', NULL, 'Genesis 4:3–26', 'Two Ways to Live and Die', 'https://soundcloud.com/user-440517750/two-ways-to-live-and-die', NULL),
  ('genesis', NULL, 'Genesis 5:1–6:8', 'God''s Preservation and Judgment of Man', 'https://soundcloud.com/user-440517750/042518p', NULL),
  ('genesis', NULL, 'Genesis 6:8–22', 'God''s Grace in a Corrupted World', 'https://soundcloud.com/user-440517750/gods-grace-in-a-corrupted-world', NULL),
  ('genesis', NULL, 'Genesis 7', 'The Omniscient, Patient God Judges', 'https://soundcloud.com/user-440517750/the-omniscience-patience-god-judges', NULL),
  ('genesis', NULL, 'Genesis 8:1–9:7', 'A New Earth but the Same Gracious God', 'https://soundcloud.com/user-440517750/a-new-earth-but-the-same-gracious-god', NULL),
  ('genesis', NULL, 'Genesis 9:8–29', 'God’s Perfect Covenant and Curse', 'https://soundcloud.com/user-440517750/gods-perfect-covenant-and-curse', NULL),
  ('genesis', NULL, 'Genesis 10–11', 'A Losing Battle Against God', 'https://soundcloud.com/user-440517750/a-losing-battle-against-god', NULL),
  ('genesis', NULL, 'Genesis 11:27–12:20', 'Man’s Faith and God’s Unthwarted Plans', 'https://soundcloud.com/user-440517750/mans-faith-and-gods-unthwarted-plans', NULL),
  ('genesis', NULL, 'Genesis 13–15', 'An Infant Nation and Its Watchful God', 'https://soundcloud.com/user-440517750/an-infant-nation-and-its-watchful-god', NULL),
  ('genesis', NULL, 'Genesis 16–17', 'The Strength of God and the Weakness of Man', 'https://soundcloud.com/user-440517750/the-strength-of-god-and-the-weakness-of-man-part-1', NULL),
  ('genesis', NULL, 'Genesis 19', 'Beauty from Ashes', 'https://soundcloud.com/user-440517750/beauty-from-ashes', NULL),
  ('genesis', NULL, 'Genesis 20', 'The Fear of Man and the Graciousness of God', 'https://soundcloud.com/user-440517750/the-fear-of-man-and-the-graciousness-of-god', NULL),
  ('genesis', NULL, 'Genesis 21', 'It''s a Boy! The Son of Promise', 'https://soundcloud.com/user-440517750/its-boy-the-son-of-promise', NULL),
  ('genesis', NULL, 'Genesis 22', 'The Sacrifice of the Beloved Son', 'https://soundcloud.com/user-440517750/the-sacrifice-of-the-beloved-son', NULL),
  ('genesis', NULL, 'Genesis 23–24', 'Faithfulness and Romance', 'https://soundcloud.com/user-440517750/faithfulness-and-romance', NULL),
  ('genesis', NULL, 'Genesis 25', 'Two Boys, Two Nations: God is Always Right!', 'https://soundcloud.com/user-440517750/two-boys-two-nations-god-is-always-right', NULL),
  ('genesis', NULL, 'Genesis 26', 'Fleeing Famine, Fighting, and Faithlessness', 'https://soundcloud.com/user-440517750/fleeing-famine-fighting-and-faithlessness', NULL),
  ('genesis', NULL, 'Genesis 27', 'The Losing Battle of Fighting God''s Will', 'https://soundcloud.com/user-440517750/the-losing-battle-of-fighting-gods-will', NULL),
  ('genesis', NULL, 'Genesis 28', 'Following the Faithfulness of God', 'https://soundcloud.com/user-440517750/following-the-faithfulness-of-god', NULL),
  ('genesis', NULL, 'Genesis 29–30', 'The Graciousness of God and the Making of a Nation', 'https://www.riverbendchurch.com/sermons/sermon/2019-03-13/the-graciousness-of-god-and-the-making-of-a-nation', NULL),
  ('genesis', NULL, 'Genesis 31', 'God''s Infant Nation is Headed Home', 'https://soundcloud.com/user-440517750/gods-infant-nation-is-headed-home', NULL),
  ('genesis', NULL, 'Genesis 32–33', 'Jacob Wrestling His Way Home!', 'https://soundcloud.com/user-440517750/jacob-wrestling-his-way-home', NULL),
  ('genesis', NULL, 'Genesis 34–36', 'Mercy and the People of God', 'https://soundcloud.com/user-440517750/mercy-and-the-people-of-god', NULL),
  ('genesis', NULL, 'Genesis 37', 'God’s Righteousness is the Only Hope for Israel', 'https://soundcloud.com/user-440517750/gods-righteousness-is-the-only-hope-for-israel', NULL),
  ('genesis', NULL, 'Genesis 38–39', 'Sex, Lies, Deception, and the Presence of God', 'https://soundcloud.com/user-440517750/sex-lies-deception-and-the-presence-of-god', NULL),
  ('genesis', NULL, 'Genesis 40', 'Waiting for God in the Darkness', 'https://soundcloud.com/user-440517750/waiting-for-god-in-the-darkness', NULL),
  ('genesis', NULL, 'Genesis 41:1–32', 'A Slave of God and the Freedom to Serve Him (Pt. 1)', 'https://soundcloud.com/user-440517750/a-slave-of-god-and-the-freedom-to-serve-him', NULL),
  ('genesis', NULL, 'Genesis 41:33–57', 'A Slave of God and the Freedom to Serve Him (Pt. 2)', 'https://soundcloud.com/user-440517750/a-slave-of-god-and-the-freedom-to-serve-him-pt-2', NULL),
  ('genesis', NULL, 'Genesis 42', 'Repentance and the Will of God', 'https://soundcloud.com/user-440517750/repentance-and-the-will-of-god', NULL),
  ('genesis', NULL, 'Genesis 43', 'Facing the Consequence of Sin', 'https://soundcloud.com/user-440517750/facing-the-consequence-of-sin', NULL),
  ('genesis', NULL, 'Genesis 44–45', 'Grace Upon Grace for the Undeserving', 'https://soundcloud.com/user-440517750/grace-upon-grace-for-the-undeserving', NULL),
  ('genesis', NULL, 'Genesis 46–47', 'When Famine Turns to Promise', 'https://soundcloud.com/user-440517750/when-famine-turns-to-promise', NULL),
  ('genesis', NULL, 'Genesis 48', 'God: The Rewarder of Those Who Diligently Seek Him', 'https://soundcloud.com/user-440517750/god-the-rewarder-of-those-who-diligently-seek-him', NULL),
  ('genesis', NULL, 'Genesis 49', 'Nation Built on the Promises of God', 'https://soundcloud.com/user-440517750/nation-built-on-the-promises-of-god', NULL),
  ('genesis', NULL, 'Genesis 50–51', 'Committed to the Covenant', 'https://soundcloud.com/user-440517750/committed-to-the-covenant', NULL),
  ('genesis', NULL, 'Genesis 1:26–27', 'Biblical Womanhood and the Character of God', 'https://youtu.be/S0NKj4b7JWs?si=mDRTOcY5i3RG9GXz', '2026-05-10'),
  ('isaiah', NULL, 'Isaiah 7:1–16', 'The Sign of Hope', 'https://soundcloud.com/user-440517750/the-sign-of-hope', NULL),
  ('isaiah', NULL, 'Isaiah 9:6–7', 'The Coming Light and Our Eternal Hope', 'https://soundcloud.com/user-440517750/the-coming-light-and-our-eternal-hope', NULL),
  ('job', NULL, 'Job 31:13–15', 'Fashioned by God', 'https://soundcloud.com/user-440517750/fashioned-by-god', NULL),
  ('john', NULL, 'John 3:1–15', 'All Members of the True Church are Born-Again Believers', 'https://youtu.be/fRnDlT4-1s8?si=iesOzCveA64nRLNs', NULL),
  ('john', NULL, 'John 5:16–30', 'Jesus and the Father', 'https://soundcloud.com/user-440517750/jesus-and-the-father', NULL),
  ('john', NULL, 'John 6:30–40', 'God''s Gift to the Son', 'https://soundcloud.com/user-440517750/gods-gift-to-the-son', NULL),
  ('john', NULL, 'John 6:51–71', 'Why Is It Hard to Love Christ?', 'https://youtu.be/q-EihS8djeo?si=oNi6RgcMlwYVXQ6X&t=1927', NULL),
  ('john', NULL, 'John 6:52–71', 'The Life-Giving, Soul-Satisfying Consumption of Jesus', 'https://soundcloud.com/user-440517750/the-life-giving-soul-satisfying-consumption-of-jesus', NULL),
  ('john', NULL, 'John 6:52–71', 'The Bread of Life or the Idols of the Heart', 'https://soundcloud.com/user-440517750/the-bread-of-life-or-the-idols-of-the-heart', NULL),
  ('john', NULL, 'John 8:48–59', 'A Death-Beating Savior and His Fearless Followers', 'https://soundcloud.com/user-440517750/a-death-beating-savior-and-his-fearless-followers', NULL),
  ('john', NULL, 'John 12:12–26', 'The Kingship of Christ', 'https://soundcloud.com/user-440517750/the-kingship-of-christ', NULL),
  ('john', NULL, 'John 12:23–33', 'The Eternal Fruit-Bearing Work of Christ''s Cross-Work', 'https://youtu.be/AYNIJlEBVFk', NULL),
  ('john', NULL, 'John 12:27–36', 'The Defining Moment of Jesus Christ''s Earthly Ministry', 'https://soundcloud.com/user-440517750/the-defining-moment-of-jesus-christs-earthly-ministry', NULL),
  ('john', NULL, 'John 12:37–50', 'Jesus and His Final Call', 'https://soundcloud.com/user-440517750/jesus-and-his-final-call', NULL),
  ('john', NULL, 'John 14:1–6', 'Preparing a Place for the Trouble-Hearted', 'https://soundcloud.com/user-440517750/preparing-a-place-for-the-troubled-hearted', NULL),
  ('john', NULL, 'John 14:15–25', 'Love Christ and You Will Be Loved by the Father', 'https://youtu.be/-4T30oVa614?si=bjpMjTY9QE-zPmN7&t=2022', NULL),
  ('john', NULL, 'John 18:37', 'Born a King', 'https://soundcloud.com/user-440517750/born-a-king', NULL),
  ('john', NULL, 'John 19:17–30', 'Jesus Christ and His Finished Work', 'https://soundcloud.com/user-440517750/jesus-christ-and-his-finished-work', NULL),
  ('john', NULL, 'John 19:28–42', 'Thank God for Friday', 'https://soundcloud.com/user-440517750/thank-god-for-friday', NULL),
  ('john', NULL, 'John 20:1–18', 'The Death-Conquering, Resurrected Savior', 'https://soundcloud.com/user-440517750/the-death-conquering-resurrected-savior', NULL),
  ('john', NULL, 'John 20:1–18', 'The Grave Could Not Hold Him!', 'https://soundcloud.com/user-440517750/the-grave-could-not-hold-him', NULL),
  ('john', NULL, 'John 20:1–18', 'Our Eternal Security and the Resurrection of Christ', 'https://youtu.be/w0iTyJSSpRo', NULL),
  ('john', NULL, 'John 20:19–20', 'The Gifts from the Resurrected Savior', 'https://soundcloud.com/user-440517750/the-gifts-from-the-resurrected-savior', NULL),
  ('leviticus', NULL, 'Leviticus 1:1', 'Introduction to Leviticus', 'https://soundcloud.com/user-440517750/introduction-to-leviticus', NULL),
  ('leviticus', NULL, 'Leviticus 1', 'The Substitutionary Sacrifice Offer to God', 'https://soundcloud.com/user-440517750/the-substitutionary-sacrifice-offer-to-god-leviticus-1', NULL),
  ('leviticus', NULL, 'Leviticus 2', 'Pleasing Offerings of Thanksgiving and Faith', 'https://soundcloud.com/user-440517750/pleasing-offerings-of-thanksgiving-and-faith', NULL),
  ('leviticus', NULL, 'Leviticus 3', 'The Peace Offering', 'https://soundcloud.com/user-440517750/the-peace-offering', NULL),
  ('leviticus', NULL, 'Leviticus 4', 'Christ: The Final Sin-Offering', 'https://soundcloud.com/user-440517750/christ-the-final-sin-offering', NULL),
  ('leviticus', NULL, 'Leviticus 5:1–6:7', 'The Sin and Guilt–Trespass Offering', 'https://soundcloud.com/user-440517750/the-sin-and-guilttrespass-offering', NULL),
  ('leviticus', NULL, 'Leviticus 6:8–30', 'A Reconciling God (Pt. 1)', 'https://soundcloud.com/user-440517750/a-reconciling-god', NULL),
  ('leviticus', NULL, 'Leviticus 6:8–7:21', 'A Reconciling God (Pt. 2)', 'https://soundcloud.com/user-440517750/a-reconciling-god-part-2', NULL),
  ('leviticus', NULL, 'Leviticus 7:22–38', 'A Shadow of the Final Atonement', 'https://soundcloud.com/user-440517750/a-shadow-of-the-final-atonement', NULL),
  ('leviticus', NULL, 'Leviticus 8', 'The Believer-Priest Is Cleansed and Set Apart for the Eternal Service to the King', 'https://soundcloud.com/user-440517750/the-believer-priest-is-cleansed-and-set-apart-for-the-eternal-service-to-the-king', NULL),
  ('leviticus', NULL, 'Leviticus 9', 'The Ministry of the High Priest', 'https://soundcloud.com/user-440517750/the-ministry-of-the-high-priest', NULL),
  ('leviticus', NULL, 'Leviticus 10', 'Our God Is a Consuming Fire', 'https://soundcloud.com/user-440517750/our-god-is-a-consuming-fire', NULL),
  ('leviticus', NULL, 'Leviticus 11', 'Be Holy Because God Is Holy', 'https://soundcloud.com/user-440517750/be-holy-because-god-is-holy', NULL),
  ('leviticus', NULL, 'Leviticus 12', 'God’s Reconciling Love for Women and Children', 'https://soundcloud.com/user-440517750/gods-reconciling-love-for-women-and-children', NULL),
  ('leviticus', NULL, 'Leviticus 13', 'The Test for Leprosy and the Nature of Indwelling Sin', 'https://soundcloud.com/user-440517750/the-test-for-leprosy-and-the-nature-of-indwelling-sin', NULL),
  ('leviticus', NULL, 'Leviticus 14', 'Those Cleansed of the Disease of Sin Worship God’s Way', 'https://soundcloud.com/user-440517750/those-cleansed-of-the-disease-of-sin-worship-gods-way', NULL),
  ('leviticus', NULL, 'Leviticus 15', 'The Cleansing of Hidden Sin', 'https://soundcloud.com/user-440517750/the-cleansing-of-hidden-sin', NULL),
  ('leviticus', NULL, 'Leviticus 16', 'The Greater Day of Atonement', 'https://soundcloud.com/user-440517750/the-greater-day-of-atonement', NULL),
  ('leviticus', NULL, 'Leviticus 17', 'Life Is in the Blood', 'https://soundcloud.com/user-440517750/life-is-in-the-blood', NULL),
  ('leviticus', NULL, 'Leviticus 18', 'God’s Warning Against the Destructive Nature of Sexual Sin', 'https://soundcloud.com/user-440517750/gods-warning-against-the-destructive-nature-of-sexual-sin', NULL),
  ('leviticus', NULL, 'Leviticus 19', 'Daily Holiness', 'https://soundcloud.com/user-440517750/daily-holiness', NULL),
  ('leviticus', NULL, 'Leviticus 19–20', 'Daily Holiness and the Penalties of Breaking God’s Law', 'https://soundcloud.com/user-440517750/daily-holiness-and-the-penalties-of-breaking-gods-law', NULL),
  ('leviticus', NULL, 'Leviticus 21', 'Perfection and the Presence of God', 'https://soundcloud.com/user-440517750/perfection-and-the-presence-of-god', NULL),
  ('leviticus', NULL, 'Leviticus 23', 'God Has Always Assembled His People', 'https://soundcloud.com/user-440517750/god-has-always-assembled-his-people', NULL),
  ('leviticus', NULL, 'Leviticus 24', 'Responding to the Holiness of God', 'https://soundcloud.com/user-440517750/responding-to-the-holiness-of-god', NULL),
  ('leviticus', NULL, 'Leviticus 25', 'Be Joyful in Your Freedom from Slavery', 'https://soundcloud.com/user-440517750/be-joyful-in-your-freedom-from-slavery', NULL),
  ('leviticus', NULL, 'Leviticus 26', 'The Blessings and Cursings of Our Covenant-Keeping God', 'https://soundcloud.com/user-440517750/the-blessings-and-cursings-of-our-covenant-keeping-god', NULL),
  ('leviticus', NULL, 'Leviticus 27', 'The Worthiness of God and the Response of His Children', 'https://soundcloud.com/user-440517750/the-worthiness-of-god-and-the-response-of-his-children', NULL),
  ('luke', NULL, 'Luke 1:1–4', 'An Introduction to the Book of Luke', 'https://youtu.be/oouYsIfeVa4?si=RzRKFMat3qG00PbW', NULL),
  ('luke', NULL, 'Luke 1:5–25', 'The Promised Forerunner to the Coming Messiah', 'https://youtu.be/YAoebv94a0c', NULL),
  ('luke', NULL, 'Luke 1:5–25', 'The Joy of the Forerunner of Christ', 'https://youtu.be/OeoqUNgPCs4?si=1xDYBQVUjTJYmztA', '2025-12-08'),
  ('luke', NULL, 'Luke 1:26–38', 'The Virgin Birth of the Holy Child for a Perfect Salvation', 'https://youtu.be/M2DF_TOUjHY?si=V58K3rNSoYgRpYSX', '2025-12-14'),
  ('luke', NULL, 'Luke 1:26–38', 'Faith, Righteousness, and the Gift of a Christ-Centered Christmas', 'https://youtu.be/GSQ5YJ-mt_E?si=Xlyveo5ufg0mWoVE&t=2881', NULL),
  ('luke', NULL, 'Luke 1:26–38', 'He Will Be Great', 'https://soundcloud.com/user-440517750/he-will-be-great', NULL),
  ('luke', NULL, 'Luke 1:26–38', 'The Matchless and Magnificent Announcement of the Coming of Christ (Pt. 1)', 'https://soundcloud.com/user-440517750/the-matchless-and-magnificent-announcement-of-the-coming-christ-part-1', NULL),
  ('luke', NULL, 'Luke 1:26–38', 'The Greatest Announcement: The Incarnation', 'https://youtu.be/ZIPL7e9eYp4', NULL),
  ('luke', NULL, 'Luke 1:31–38', 'The Matchless and Magnificent Announcement of the Coming of Christ (Pt. 2)', 'https://soundcloud.com/user-440517750/the-matchless-and-magnificent-announcement-of-the-coming-christ-part-2', NULL),
  ('luke', NULL, 'Luke 1:39–80', 'God''s Salvation Plan Involved God-Fearing Worshippers', 'https://youtu.be/7HH0ebo9QTI?si=tbllLmaH9NAxgRaF', '2025-12-21'),
  ('luke', NULL, 'Luke 1:46–56', 'Mary''s Worship', 'https://www.riverbendchurch.com/sermons/sermon/2022-12-18/mary-s-worship', NULL),
  ('luke', NULL, 'Luke 2:1–6', 'The Night Before', 'https://soundcloud.com/user-440517750/the-night-before', NULL),
  ('luke', NULL, 'Luke 2:1–7', 'The Wonderful, Merciful Savior is Born', 'https://soundcloud.com/user-440517750/the-wonderful-merciful-savior-is-born', NULL),
  ('luke', NULL, 'Luke 2:1–20', 'There Has Been Born for You a Savior', 'https://soundcloud.com/user-440517750/there-has-been-born-for-you-a-savior', NULL),
  ('luke', NULL, 'Luke 2:1–20', 'Behold His Glory and Receive His Peace', 'https://soundcloud.com/user-440517750/behold-his-glory-and-receive-his-peace', NULL),
  ('luke', NULL, 'Luke 2:1–20', 'From Rags to Riches', 'https://soundcloud.com/user-440517750/from-rags-to-riches', NULL),
  ('luke', NULL, 'Luke 2:1–20', 'We Need a Savior Who is Christ the Lord', 'https://youtu.be/r12C_JO7_UQ', NULL),
  ('luke', NULL, 'Luke 2:7–20', 'The Birth of Christ and the Glory of God', 'https://soundcloud.com/user-440517750/the-birth-of-christ-and-the-glory-of-god', NULL),
  ('luke', NULL, 'Luke 2:10', 'Incarnational Joy', 'https://soundcloud.com/user-440517750/incarnational-joy', NULL),
  ('luke', NULL, 'Luke 2:14', 'Only a True Savior Can Bring True Peace', 'https://soundcloud.com/user-440517750/only-a-true-savior-can-bring-true-peace', NULL),
  ('luke', NULL, 'Luke 2:21–38', 'Jesus is Named and the Faithful Rejoice', 'https://youtu.be/SYJZAL8lpz0?si=ssHwVnVRI8iRbmn9', '2025-12-28'),
  ('luke', NULL, 'Luke 2:39–52', 'The God-Child', 'https://youtu.be/FoKvURLtHt0?si=XB7lf1zg34hxRoJT', '2026-01-04'),
  ('luke', NULL, 'Luke 3:1–6', 'The Salvation of God in a Spiritually-Dead Climate', 'https://youtu.be/WOCfxUS2fqo?si=kabZkYYGhYXqsL7n', '2026-01-11'),
  ('luke', NULL, 'Luke 3:4–14', 'Two Baptisms and Two Eternal Destinations, Pt. 1', 'https://youtu.be/UlRFsItoJdQ?si=VHNZ77TAviCZkCdU', '2026-01-18'),
  ('luke', NULL, 'Luke 3:15–20', 'Two Baptisms and Two Eternal Destinations, Pt. 2', 'https://youtu.be/iwUWHkPbhy4?si=1dx4bS4cEoPME81F', '2026-01-18'),
  ('luke', NULL, 'Luke 3:21', 'The Identifying Testimony of the Godhead', 'https://youtu.be/o3yAEPkzwMQ?si=C9pFksv7JguaLp9M', '2026-02-01'),
  ('luke', NULL, 'Luke 3:22', 'The Father''s Identifying Work and the Spirit''s Power in the Life of Christ', 'https://youtu.be/ZLIMkWzznVA?si=Huc9J2MuJJ-nej9a', '2026-02-08'),
  ('luke', NULL, 'Luke 3:23–38', 'These Things Are Written That You May Believe', 'https://youtu.be/Iw1sCyugk1k?si=S_Ju8in9D5ugiEuG', '2026-02-22'),
  ('luke', NULL, 'Luke 4:1–8', 'Satan Attacks the Character of God through the Temptation of Christ', 'https://youtu.be/RzeGlkScpH0?si=ozLBYiz9x6gFQYsb', '2026-03-01'),
  ('luke', NULL, 'Luke 4:9–13', 'The Temptation of the Crown Before the Cross', 'https://youtu.be/RXdvECjlZGY?si=LeEIckrlARqvEreH', '2026-03-08'),
  ('luke', NULL, 'Luke 4:14–22', 'Only the Spiritually Bankrupt Receive the Gospel', 'https://youtu.be/I8ZubJ3cfpk?si=iauSp4Mw3Dc5-Bjh', '2026-03-29'),
  ('luke', NULL, 'Luke 4:23–30', 'The Deadly Heart of Self-Righteousness', 'https://youtu.be/pONjLtOrYRA?si=PRWJHXkcVZgooiAK', '2026-04-12'),
  ('luke', NULL, 'Luke 4:31–37', 'The Preaching Ministry of Christ and Its Ability to Expose the Dark Spirit World', 'https://www.youtube.com/watch?v=XDYgm9UvvaQ', '2026-05-24'),
  ('luke', NULL, 'Luke 4:38–40', 'Christ''s Power Over Disease and Demons Points to the Power of the Gospel', 'https://www.youtube.com/watch?v=1o82FlclR28', '2026-05-31'),
  ('luke', NULL, 'Luke 4:41–44', 'The One and Only True Deliverer', 'https://youtu.be/LR1l2zqhlGc?si=Ab8OGGVuN9D3Mndv', '2026-06-07'),
  ('luke', NULL, 'Luke 7:36–50', 'A Heart of Thanksgiving Through Contentment', 'https://youtu.be/81vb3zgnHFE', NULL),
  ('luke', NULL, 'Luke 16:19–31', 'Hell is Filled with Religious People', 'https://soundcloud.com/user-440517750/hell-is-filled-with-religious-people', NULL),
  ('luke', NULL, 'Luke 23:33–49', 'The Innocent, Crucified Savior', 'https://youtu.be/V_kJlWF0-PA', NULL),
  ('luke', NULL, 'Luke 24:1–12', 'Unbelief Could Not Stop the Resurrection', 'https://soundcloud.com/user-440517750/unbelief-could-not-stop-the-resurrection', NULL),
  ('luke', NULL, 'Luke 24:50–53', 'The Glorious and Joyful Message of the Resurrection', 'https://soundcloud.com/user-440517750/the-glorious-and-joyful-message-of-the-resurrection', NULL),
  ('mark', NULL, 'Mark 1:1', 'An Introduction to the Book of Mark', 'https://soundcloud.com/user-440517750/an-introduction-to-the-book-of-mark', NULL),
  ('mark', NULL, 'Mark 1:1–8', 'The Good News of God and His Messengers', 'https://soundcloud.com/user-440517750/the-good-news-of-god-and-his-messengers', NULL),
  ('mark', NULL, 'Mark 1:9–13', 'Jesus, the Greatest Servant of All', 'https://soundcloud.com/user-440517750/jesus-the-greatest-servant-of-all', NULL),
  ('mark', NULL, 'Mark 1:14–15', 'The Greatest Moment in Time', 'https://soundcloud.com/user-440517750/the-greatest-moment-in-time', NULL),
  ('mark', NULL, 'Mark 1:16–28', 'The Unmistakable Power, Wisdom, and Authority of Jesus', 'https://soundcloud.com/user-440517750/the-unmistakable-power-wisdom-and-authority-of-jesus', NULL),
  ('mark', NULL, 'Mark 1:29–45', 'Jesus and His Perfect, Purpose-Driven Life', 'https://soundcloud.com/user-440517750/jesus-and-his-perfect-purpose-driven-life', NULL),
  ('mark', NULL, 'Mark 2:1–5', 'The Compassionate Healer Who Forgives Sins', 'https://soundcloud.com/user-440517750/the-compassionate-healer-who-forgives-sins', NULL),
  ('mark', NULL, 'Mark 2:5–13', 'The Authority of the Son of God', 'https://soundcloud.com/user-440517750/the-authority-of-the-son-of-god', NULL),
  ('mark', NULL, 'Mark 2:14–22', 'Inside the Ministry of Jesus', 'https://soundcloud.com/user-440517750/inside-the-ministry-of-jesus', NULL),
  ('mark', NULL, 'Mark 2:23–31', 'Worship, Our True Spiritual Fuel', 'https://soundcloud.com/user-440517750/worship-our-true-spiritual-fuel', NULL),
  ('mark', NULL, 'Mark 3:1–12', 'The Sabbath Showdown', 'https://soundcloud.com/user-440517750/the-sabbath-showdown', NULL),
  ('mark', NULL, 'Mark 3:13–19', 'The Greatest Example of Making Disciples', 'https://soundcloud.com/user-440517750/the-greatest-examples-of-making-disciples', NULL),
  ('mark', NULL, 'Mark 3:20–35', 'Messiah or Madman?', 'https://soundcloud.com/user-440517750/messiah-or-madman', NULL),
  ('mark', NULL, 'Mark 3:31–35', 'Jesus and His Forever Family', 'https://soundcloud.com/user-440517750/jesus-and-his-forever-family', NULL),
  ('mark', NULL, 'Mark 4:1–12', 'The Soils of the Heart of Man (Pt. 1)', 'https://soundcloud.com/user-440517750/the-soils-of-the-heart-of-man-part-1', NULL),
  ('mark', NULL, 'Mark 4:13–20', 'The Soils of the Heart of Man (Pt. 2)', 'https://soundcloud.com/user-440517750/the-soils-of-the-heart-of-man-part-2', NULL),
  ('mark', NULL, 'Mark 4:21–34', 'The Gospel Harvest', 'https://soundcloud.com/user-440517750/the-gospel-harvest', NULL),
  ('mark', NULL, 'Mark 4:30–31', 'Taking Refuge in Christ Our Creator', 'https://soundcloud.com/user-440517750/taking-refuge-in-christ-our-creator', NULL),
  ('mark', NULL, 'Mark 5:1–20', 'Supernatural Power to Cast Out and to Draw In', 'https://soundcloud.com/user-440517750/supernatural-power-to-cast-out-and-to-draw-in', NULL),
  ('mark', NULL, 'Mark 5:21–43', 'Focus on the Lesser and You Will Miss the Greater!', 'https://soundcloud.com/user-440517750/focus-on-the-lesser-and-you-will-miss-the-greater', NULL),
  ('mark', NULL, 'Mark 6:1–6', 'The Deadliness of Unbelief', 'https://soundcloud.com/user-440517750/the-deadliness-of-unbelief', NULL),
  ('mark', NULL, 'Mark 6:14–32', 'The Forerunner and a Godless King', 'https://soundcloud.com/user-440517750/the-forerunner-and-a-godless-king', NULL),
  ('mark', NULL, 'Mark 6:33–44', 'Lessons from the Good Shepherd', 'https://soundcloud.com/user-440517750/lessons-from-the-good-shepherd', NULL),
  ('mark', NULL, 'Mark 6:45–56', 'The Incomparable Great Shepherd', 'https://soundcloud.com/user-440517750/the-incomparable-great-shepherd', NULL),
  ('mark', NULL, 'Mark 7:1–13', 'All-Knowing Jesus and the Heart of Man', 'https://soundcloud.com/user-440517750/all-knowing-jesus-and-the-heart-of-man', NULL),
  ('mark', NULL, 'Mark 7:14–23', 'Jesus Reveals the True Heart of Defilement', 'https://soundcloud.com/user-440517750/jesus-reveals-the-true-heart-of-defilement', NULL),
  ('mark', NULL, 'Mark 7:24–30', 'A Relentless God-Given Faith', 'https://soundcloud.com/user-440517750/a-relentless-god-given-faith', NULL),
  ('mark', NULL, 'Mark 7:31–37', 'The Great Sovereign Physician', 'https://soundcloud.com/user-440517750/the-great-sovereign-physician', NULL),
  ('mark', NULL, 'Mark 8:1–10', 'Life Lessons from the Master', 'https://soundcloud.com/user-440517750/050519alife-lessons-from-the-master', NULL),
  ('mark', NULL, 'Mark 8:11–26', 'Lord, Let Me See You!', 'https://soundcloud.com/user-440517750/lord-let-me-see-you', NULL),
  ('mark', NULL, 'Mark 8:27–33', 'God''s Plan or Yours?', 'https://soundcloud.com/user-440517750/gods-plan-or-yours', NULL),
  ('mark', NULL, 'Mark 8:34–38', 'Trademarks of True Christianity', 'https://soundcloud.com/user-440517750/trademarks-of-true-christianity', NULL),
  ('mark', NULL, 'Mark 9:1–13', 'The Kindness of God and a Glimpse of the Kingdom (Pt. 1)', 'https://soundcloud.com/user-440517750/the-kindness-of-god-and-a-glimpse-of-the-kingdom', NULL),
  ('mark', NULL, 'Mark 9:1–13', 'The Kindness of God and a Glimpse of the Kingdom (Pt. 2)', 'https://soundcloud.com/user-440517750/the-kindness-of-god-and-a-glimpse-of-the-kingdom-pt-2', NULL),
  ('mark', NULL, 'Mark 9:14–29', 'A God-Given Faith and a Life of Prayer', 'https://soundcloud.com/user-440517750/a-god-given-faith-and-a-life-of-prayer', NULL),
  ('mark', NULL, 'Mark 9:30–37', 'A Humility-Creating Gospel', 'https://soundcloud.com/user-440517750/a-humility-creating-gospel', NULL),
  ('mark', NULL, 'Mark 9:38–50', 'Self-Righteous Pride that Creates Flavorless Christianity', 'https://soundcloud.com/user-440517750/self-righteous-pride-that-creates-flavorless-christianity', NULL),
  ('mark', NULL, 'Mark 10:1–12', 'Recovering a Biblical View of Marriage and Divorce', 'https://soundcloud.com/user-440517750/recovering-a-biblical-view-of-marriage-and-divorce', NULL),
  ('mark', NULL, 'Mark 10:13–16', 'Saving Faith that Receives the King and His Kingdom', 'https://soundcloud.com/user-440517750/saving-faith-that-receives-the-king-and-his-kingdom', NULL),
  ('mark', NULL, 'Mark 10:17–31', 'Our Humanly Impossible Salvation', 'https://soundcloud.com/user-440517750/our-humanly-impossible-salvation', NULL),
  ('mark', NULL, 'Mark 10:32–34', 'The Cross Before Him', 'https://soundcloud.com/user-440517750/the-cross-before-him', NULL),
  ('mark', NULL, 'Mark 10:35–45', 'Revealing and Correcting the Lack of Humility', 'https://soundcloud.com/user-440517750/revealing-and-correcting-the-lack-of-humility', NULL),
  ('mark', NULL, 'Mark 10:46–52', 'Salvation: A Miracle of Mercy', 'https://soundcloud.com/user-440517750/salvation-a-miracle-of-mercy', NULL),
  ('mark', NULL, 'Mark 11:1–11', 'The Praise of the Faithful and the Faithless', 'https://soundcloud.com/user-440517750/the-praise-of-the-faithful-and-the-faithless', NULL),
  ('mark', NULL, 'Mark 11:12–25', 'Religious but Unfruitful', 'https://soundcloud.com/user-440517750/religious-but-unfruitful', NULL),
  ('mark', NULL, 'Mark 11:19–26', 'Lessons from a Dead Tree', 'https://soundcloud.com/user-440517750/lessons-from-a-dead-tree', NULL),
  ('mark', NULL, 'Mark 11:27–33', 'The Divine Authority of Christ', 'https://soundcloud.com/user-440517750/the-divine-authority-of-christ', NULL),
  ('mark', NULL, 'Mark 12:1–12', 'A Parable of Prophecy and Truth', 'https://soundcloud.com/user-440517750/a-parable-of-prophecy-and-truth', NULL),
  ('mark', NULL, 'Mark 12:13–17', 'Christ Exposes Hypocrisy and Reveals Truth', 'https://soundcloud.com/user-440517750/christ-exposes-hypocrisy-and-reveals-truth', NULL),
  ('mark', NULL, 'Mark 12:18–27', 'The God of the Living', 'https://soundcloud.com/user-440517750/the-god-of-the-living', NULL),
  ('mark', NULL, 'Mark 12:28–34', 'The Love of God and Those Who Find It', 'https://soundcloud.com/user-440517750/the-love-of-god-and-those-who-find-it', NULL),
  ('mark', NULL, 'Mark 12:34–40', 'Christ the Narrow Gate and His Detractors', 'https://soundcloud.com/user-440517750/christ-the-narrow-gate-and-his-detractors', NULL),
  ('mark', NULL, 'Mark 12:38–44', 'The Truth of Christ is Greater Than the Lies of Deception', 'https://soundcloud.com/user-440517750/the-truth-of-christ-is-greater-than-the-lies-of-deception', NULL),
  ('mark', NULL, 'Mark 13:1–13', 'The Church Built on Christ Alone Has Nothing to Fear', 'https://soundcloud.com/user-440517750/the-church-built-on-christ-alone-has-nothing-to-fear', NULL),
  ('mark', NULL, 'Mark 13:14–23', 'The Darkness Before the Light', 'https://soundcloud.com/user-440517750/the-darkness-before-the-light', NULL),
  ('mark', NULL, 'Mark 13:24–37', 'The Return of the King', 'https://soundcloud.com/user-440517750/the-return-of-the-king', NULL),
  ('mark', NULL, 'Mark 14:1–11', 'The Works of Haters, Pretenders, and Worshippers of Christ', 'https://soundcloud.com/user-440517750/the-works-of-haters-pretenders-and-worshippers-of-christ', NULL),
  ('mark', NULL, 'Mark 14:12–21', 'The Betrayer’s Blindness to the Sovereign Savior', 'https://soundcloud.com/user-440517750/the-betrayers-blindness-to-the-sovereign-savior', NULL),
  ('mark', NULL, 'Mark 14:22–26', 'The Lord’s Table and Our Eternal Hope', 'https://soundcloud.com/user-440517750/the-lords-table-and-our-eternal-hope', NULL),
  ('mark', NULL, 'Mark 14:27–42', 'The Preparations of the Suffering Servant', 'https://soundcloud.com/user-440517750/the-preparations-of-the-suffering-servant', NULL),
  ('mark', NULL, 'Mark 14:43–52', 'The Arrest of the Suffering Servant', 'https://soundcloud.com/user-440517750/the-arrest-of-the-suffering-servant', NULL),
  ('mark', NULL, 'Mark 14:53–65', 'The Trial of the Suffering Servant', 'https://soundcloud.com/user-440517750/the-trial-of-the-suffering-servant', NULL),
  ('mark', NULL, 'Mark 14:66–72', 'The Denial of the Suffering Servant', 'https://soundcloud.com/user-440517750/the-denial-of-the-suffering-servant', NULL),
  ('mark', NULL, 'Mark 15:1–15', 'The Verdict and the Suffering Servant', 'https://soundcloud.com/user-440517750/the-verdict-and-the-suffering-servant', NULL),
  ('mark', NULL, 'Mark 15:16–25', 'The Crushing of the Suffering Servant', 'https://soundcloud.com/user-440517750/the-crushing-of-the-suffering-servant', NULL),
  ('mark', NULL, 'Mark 15:26–32', 'The Suffering Servant is the King of Kings', 'https://soundcloud.com/user-440517750/the-suffering-servant-is-the-king-of-kings', NULL),
  ('mark', NULL, 'Mark 15:33–39', 'The Finished Work of the Suffering Servant', 'https://soundcloud.com/user-440517750/the-finished-work-of-the-suffering-servant', NULL),
  ('mark', NULL, 'Mark 15:40–47', 'The Power of the Cross of Christ', 'https://soundcloud.com/user-440517750/the-power-of-the-cross-of-christ', NULL),
  ('mark', NULL, 'Mark 16:1–8', 'The Resurrection: The Truth Worthy of Life and Death', 'https://soundcloud.com/user-440517750/the-resurrection-the-truth-worthy-of-life-and-death', NULL),
  ('mark', NULL, 'Mark 16:1–8', 'Come and Be Amazed at the Resurrection of Christ', 'https://youtu.be/4lshvRclpqU?si=tCzBhavz5qYtoPzR', '2025-04-05'),
  ('mark', NULL, 'Mark 16:9–14', 'My Lord and My God', 'https://soundcloud.com/user-440517750/my-lord-and-my-god', NULL),
  ('mark', NULL, 'Mark 16:15–20', 'The Unstoppable Gospel of God', 'https://soundcloud.com/user-440517750/the-unstoppable-gospel-of-god', NULL),
  ('matthew', NULL, 'Matthew 1', 'A Global Christmas', 'https://soundcloud.com/user-440517750/a-global-christmas', NULL),
  ('matthew', NULL, 'Matthew 1:18–25', 'The Miracle that Gave Us Christmas', 'https://soundcloud.com/user-440517750/the-miracle-that-gave-us-christmas', NULL),
  ('matthew', NULL, 'Matthew 1:18–25', 'A Birth Like No Other', 'https://soundcloud.com/user-440517750/a-birth-like-no-other', NULL),
  ('matthew', NULL, 'Matthew 1:18–25', 'The Fall of Mankind and Christmas (Pt. 1)', 'https://soundcloud.com/user-440517750/the-fall-of-mankind-and-christmas', NULL),
  ('matthew', NULL, 'Matthew 1:18–25', 'The Fall of Mankind and Christmas (Pt. 2)', 'https://soundcloud.com/user-440517750/the-fall-of-mankind-and-christmas-part-2', NULL),
  ('matthew', NULL, 'Matthew 1:18–25', 'You Shall Call His Name Jesus', 'https://youtu.be/qOecB3Nf2VM?si=Gpf22nBwjq0nhsda&t=2068', NULL),
  ('matthew', NULL, 'Matthew 2:1–12', 'A Few Wise Men Still Seek Him', 'https://youtu.be/UHIISWBXqkc?si=ywUL6YoB3kUymylj&t=2182', NULL),
  ('matthew', NULL, 'Matthew 2:1–12', 'Are You Looking for the King of Kings?', 'https://soundcloud.com/user-440517750/are-you-looking-for-the-king-of-kings', NULL),
  ('matthew', NULL, 'Matthew 6:25–34', 'The Comfort of Trusting God', 'https://soundcloud.com/user-440517750/the-comfort-of-trusting-god', NULL),
  ('matthew', NULL, 'Matthew 7:13–27', 'Do You Know the Jesus of the Bible?', 'https://youtu.be/9XNwxEwpGX4', NULL),
  ('matthew', NULL, 'Matthew 8:23–27', 'The Creator and Calmer of Storms', 'https://soundcloud.com/user-440517750/the-creator-and-calmer-of-storms', NULL),
  ('matthew', NULL, 'Matthew 16:13–20', 'God''s Deep Love for the Church, Pt. 1', 'https://youtu.be/EPrxUx4iqZA', NULL),
  ('matthew', NULL, 'Matthew 18:1–14', 'The Dangerous Desire for Greatness', 'https://soundcloud.com/user-440517750/the-dangerous-desire-for-greatness', NULL),
  ('matthew', NULL, 'Matthew 18:15–20', 'Church Discipline and the Love of God', 'https://soundcloud.com/user-440517750/church-discipline-and-the-love-of-god', NULL),
  ('matthew', NULL, 'Matthew 26:26–29', 'The Gospel and the Ordinances', 'https://soundcloud.com/user-440517750/the-gospel-and-the-ordinances', NULL),
  ('matthew', NULL, 'Matthew 27:57–28:20', 'The Resurrected King', 'https://soundcloud.com/user-440517750/the-resurrected-king', NULL),
  ('micah', NULL, 'Micah 5:1–2', 'The Savior of Nobodies', 'https://soundcloud.com/user-440517750/the-savior-of-nobodies', NULL),
  ('numbers', NULL, 'Numbers 1', 'Preparing for the Border of the Promise Land', 'https://soundcloud.com/user-440517750/preparing-for-the-border-of-the-promise-land', NULL),
  ('numbers', NULL, 'Numbers 2–3', 'Our God of Organization and Worship', 'https://soundcloud.com/user-440517750/our-god-of-organization-and-worship', NULL),
  ('numbers', NULL, 'Numbers 4', 'The Worship of the Unnoticed', 'https://soundcloud.com/user-440517750/the-worship-of-the-unnoticed', NULL),
  ('numbers', NULL, 'Numbers 5', 'Dwelling with a Holy God', 'https://soundcloud.com/user-440517750/dwelling-with-a-holy-god', NULL),
  ('numbers', NULL, 'Numbers 6:1–21', 'A Vow of Separation for the Glory of God', 'https://soundcloud.com/user-440517750/a-vow-of-separation-for-the-glory-of-god', NULL),
  ('numbers', NULL, 'Numbers 6:22–27', 'A Glorious Benediction', 'https://soundcloud.com/user-440517750/a-glorious-benediction', NULL),
  ('numbers', NULL, 'Numbers 7', 'Dedication and Adornment', 'https://soundcloud.com/user-440517750/dedication-and-adornment', NULL),
  ('numbers', NULL, 'Numbers 8', 'Preparation for the Promise Land', 'https://soundcloud.com/user-440517750/preparation-for-the-promise-land', NULL),
  ('numbers', NULL, 'Numbers 9:1–10:10', 'God''s Divine Provisions to Reach the Promise Land', 'https://soundcloud.com/user-440517750/gods-divine-provisions-to-reach-the-promised-land', NULL),
  ('numbers', NULL, 'Numbers 10:11–36', 'An Epic Departure for the Promise Land', 'https://soundcloud.com/user-440517750/an-epic-departure-for-the-promised-land', NULL),
  ('numbers', NULL, 'Numbers 11', 'The Graveyards of the Faithless on the Way to the Promised Land', 'https://soundcloud.com/user-440517750/the-graveyards-of-the-faithless-on-the-way-to-the-promised-land', NULL),
  ('numbers', NULL, 'Numbers 12', 'A Humble Mediator and a Deadly Jealousy', 'https://soundcloud.com/user-440517750/a-humble-mediator-and-a-deadly-jealousy', NULL),
  ('numbers', NULL, 'Numbers 13', 'Espionage and the Plan of God', 'https://soundcloud.com/user-440517750/espionage-and-the-plan-of-god', NULL),
  ('numbers', NULL, 'Numbers 14', 'Wreckage in a Wilderness of Unbelief', 'https://soundcloud.com/user-440517750/wreckage-in-a-wilderness-of-unbelief', NULL),
  ('numbers', NULL, 'Numbers 15', 'Learning from the Past while Preparing for the Future', 'https://soundcloud.com/user-440517750/learning-from-the-past-while-preparing-for-the-future', NULL),
  ('numbers', NULL, 'Numbers 16', 'A God Who Protects His Gospel', 'https://soundcloud.com/user-440517750/a-god-who-protects-his-gospel', NULL),
  ('numbers', NULL, 'Numbers 17', 'Aaron''s Rod and New Life in Christ', 'https://soundcloud.com/user-440517750/aarons-rod-and-new-life-in-christ', NULL),
  ('numbers', NULL, 'Numbers 18', 'Who Can Come into the Presence of God?', 'https://soundcloud.com/user-440517750/who-can-come-into-the-presence-of-god', NULL),
  ('numbers', NULL, 'Numbers 19', 'A Red Heifer and the Purifying Work of Christ', 'https://soundcloud.com/user-440517750/041923pa-red-heifer-and-the-purifying-work-of-christ', NULL),
  ('numbers', NULL, 'Numbers 20', 'Loving and Obeying God When It Hurts', 'https://soundcloud.com/user-440517750/loving-and-obeying-god-when-it-hurts', NULL),
  ('numbers', NULL, 'Numbers 21:1–9', 'Look and Live!', 'https://youtu.be/ZVWxFBkIFiA?si=Epj3P2AP_m852SaL&t=1410', NULL),
  ('numbers', NULL, 'Numbers 21:1–9', 'The Poison of Sin and a Savior Cursed for Us', 'https://youtu.be/fy-csGnFR-E?si=mWMx2rVvXIpoz2Us', '2026-05-17'),
  ('numbers', NULL, 'Numbers 21:10–35', 'God’s Often Unseen Protection', 'https://youtu.be/oX2EMuusLy4?si=yCdjYn_MsJ2wES7I&t=1273', NULL),
  ('numbers', NULL, 'Numbers 22', 'The Christ-Like Donkey and a Foolish False Prophet', 'https://youtu.be/nJk-OmUyveo?si=VRw-r1-SShENgIQP&t=1093', NULL),
  ('numbers', NULL, 'Numbers 23–24', 'The Watcher''s Secret Care of His People', 'https://youtu.be/7hWKOZuUkk4?si=KJAKy_2F_WNClKr9&t=1158', NULL),
  ('numbers', NULL, 'Numbers 25', 'A Holy God and a Deadly Atonement', 'https://youtu.be/7hWKOZuUkk4?si=KJAKy_2F_WNClKr9&t=1158', NULL),
  ('numbers', NULL, 'Numbers 26–27', 'God Provides a New Generation, a New Land, and a New Leader', 'https://youtu.be/nK2pf_15Jm0?si=PuAQffGsv_f4GUFR&t=1180', NULL),
  ('numbers', NULL, 'Numbers 28–29', 'A Shadow of Greater Things to Come', 'https://youtu.be/gDLF8NosgCA?si=BMHs3Awy2DMTjdoL&t=1069', NULL),
  ('numbers', NULL, 'Numbers 30', 'The Grace of God and Unanswered Prayers', 'https://youtu.be/BZeqWRRTFxA?si=kcf72-R7qzXp7pfx&t=1639', NULL),
  ('numbers', NULL, 'Numbers 31', 'The Judge of All the Earth is Right', 'https://youtu.be/27Z5tbTGWcM?si=B16IIgKhLn7iSEpx&t=1063', NULL),
  ('numbers', NULL, 'Numbers 32', 'Leading God’s People through the Dangers of the Heart', 'https://youtu.be/cRmLflo8Cp4?si=RPplezFg9qJ7nMza&t=1110', NULL),
  ('numbers', NULL, 'Numbers 33', 'The Hearts of Those Who Inhabit the Promise Land', 'https://youtu.be/21jhKxdqpXw?si=jAbGq5ztRcTZ3Rg5&t=1198', NULL),
  ('numbers', NULL, 'Numbers 34', 'God''s Habit of Giving What is Undeserved', 'https://youtu.be/gu3JbJ-N6jE?si=NZtKUU_pztdswf08&t=1115', NULL),
  ('numbers', NULL, 'Numbers 35–36', 'Our Hiding Place is in the Grace of God (Pt. 1)', 'https://youtu.be/NlFP3mzFcX0?si=dSwDC8Xf_TUGajTy&t=938', NULL),
  ('numbers', NULL, 'Numbers 35–36', 'Our Hiding Place is in the Grace of God (Pt. 2)', 'https://youtu.be/nW92n1fI3IY?si=w9U-NeWkyAFxFR0J&t=925', NULL),
  ('numbers', NULL, 'Numbers', 'An Introduction to the Book of Numbers', 'https://soundcloud.com/user-440517750/an-introduction-to-the-book-of-numbers', NULL),
  ('philippians', NULL, 'Philippians 1:8–11', 'The Joyful Gospel and God''s Will', 'https://soundcloud.com/user-440517750/the-joyful-gospel-and-gods-will-philippians-18-11', NULL),
  ('philippians', NULL, 'Philippians 3:12–16', 'Pursuing the Prize of Christ', 'https://soundcloud.com/user-440517750/pursuing-the-prize-of-christ', NULL),
  ('philippians', NULL, 'Philippians 4:4–9', 'The Lord is Near', 'https://soundcloud.com/user-440517750/the-lord-is-near', NULL),
  ('philippians', NULL, 'Philippians 4:6–9', 'Our Savior and Our Anxieties', 'https://soundcloud.com/user-440517750/our-savior-and-our-anxieties', NULL),
  ('philippians', NULL, 'Philippians 4:8–14', 'Contentment in Christ and His Word (Pt. 1)', 'https://soundcloud.com/user-440517750/contentment-in-christ-and-his-word', NULL),
  ('philippians', NULL, 'Philippians 4:9–14', 'Contentment in Christ and His Word (Pt. 2)', 'https://soundcloud.com/user-440517750/040520acontentment-in-christ-and-his-word-pt-2', NULL),
  ('proverbs', NULL, 'Proverbs 22:6', 'The Path of a Child', 'https://soundcloud.com/user-440517750/the-path-of-a-child', NULL),
  ('proverbs', NULL, 'Proverbs 31:25–31', 'The Beauty and Imagery of Biblical Womanhood', 'https://soundcloud.com/user-440517750/the-beauty-and-imagery-of-biblical-womanhood', NULL),
  ('proverbs', NULL, 'Proverbs 31:25–31', 'Biblical Womanhood and the Glory of God', 'https://youtu.be/CRNqpBwF-wg', NULL),
  ('psalms', NULL, 'Psalm 11', 'What Can the Righteous Do?', 'https://soundcloud.com/user-440517750/what-can-the-righteous-do', NULL),
  ('psalms', NULL, 'Psalm 16', 'Christ Our Hope in Life and Death', 'https://www.youtube.com/watch?v=EYNhpQ8fy-o', NULL),
  ('psalms', NULL, 'Psalm 19:7–14', 'Trusting and Living According to the All-Sufficient Scriptures', 'https://youtu.be/8ftWDI6Nu9Y?si=-Zj-QvUpqkwxgG7B', NULL),
  ('psalms', NULL, 'Psalm 39:1–13', 'Living in the Light of Eternity', 'https://youtu.be/-DCYd5lNCfo?si=4q1b8rGX70-AJriW&t=1688', NULL),
  ('psalms', NULL, 'Psalm 39', 'Men Who Live in Light of Eternity', 'https://youtu.be/0EKYMMx_vlA', NULL),
  ('psalms', NULL, 'Psalm 78:1–8', 'Truth and Grace and Our Children', 'https://youtu.be/avxqNpSB0SE?si=maBjBj7jn9Hg3Zht&t=1271', NULL),
  ('psalms', NULL, 'Psalm 86:11', 'Spiritual Discipline and the Means of Grace', 'https://soundcloud.com/user-440517750/spiritual-discipline-and-the-means-of-grace', NULL),
  ('psalms', NULL, 'Psalm 91', 'The Unseen Power and Protection of Our God', 'https://soundcloud.com/user-440517750/the-unseen-power-and-protection-of-our-god', NULL),
  ('psalms', NULL, 'Psalm 96:1–13', 'Worship Generates True Missional Theology', 'https://youtu.be/BnfsGODDnkM?si=l8rewsai0-4_ofVR&t=3171', NULL),
  ('psalms', NULL, 'Psalm 96:1–13', 'Declaring His Glory to the Nations', 'https://vimeo.com/showcase/249505/video/120319572', NULL),
  ('psalms', NULL, 'Psalm 104', 'The Glory of God and the Blessings of Our Souls', 'https://soundcloud.com/user-440517750/the-glory-of-god-and-the-blessings-of-our-souls', NULL),
  ('psalms', NULL, 'Psalm 111', 'The Heart of Worship', 'https://soundcloud.com/user-440517750/the-heart-of-worship', NULL),
  ('psalms', NULL, 'Psalm 111', 'A Hallelujah Thanksgiving', 'https://soundcloud.com/user-440517750/a-hallelujah-thanksgiving', NULL),
  ('psalms', NULL, 'Psalm 111', 'True Thanksgiving Flows from the Heart', 'https://youtu.be/N2qxVB7gIug?si=PETriU4kFUS61lS0', NULL),
  ('psalms', NULL, 'Psalm 131', 'David''s Inspired Recipe for Anxiety', 'https://soundcloud.com/user-440517750/davids-inspired-recipe-for-anxiety', NULL),
  ('psalms', NULL, 'Psalm 131', 'Overcoming Anxiety Through Our Hope in the Lord', 'https://www.youtube.com/watch?v=r9WQfaqYBRg', NULL),
  ('psalms', NULL, 'Psalm 135', 'Is God Great?', 'https://soundcloud.com/user-440517750/is-god-great', NULL),
  ('psalms', NULL, 'Psalm 138', 'Gospel Gratitude: The Inheritance of Thanksgiving', 'https://soundcloud.com/user-440517750/gospel-gratitude-the-inheritance-of-thanksgiving-part-1', NULL),
  ('psalms', NULL, 'Psalm 139:13-18', 'Our Omnipotent God and the Sanctity of Life', 'https://youtu.be/qQvPKwX9kP0?si=ps-ooxOAU73abFtl&t=1592', NULL),
  ('psalms', NULL, 'Psalm 141', 'Prayers of Desperation and Dependency', 'https://soundcloud.com/user-440517750/prayers-of-desperation-and-dependency', NULL),
  ('psalms', NULL, 'Psalm 11', 'What Can the Righteous Do In a Wicked World?', 'https://www.youtube.com/watch?v=cdfxTKufNak', '2026-04-26'),
  ('revelation', NULL, 'Revelation 1:1–8', 'The Incomparable and Unrivaled Lord Jesus (Pt. 1)', 'https://soundcloud.com/user-440517750/the-incomparable-and-unrivaled-lord-jesus-christ', NULL),
  ('revelation', NULL, 'Revelation 1:9–18', 'The Incomparable and Unrivaled Lord Jesus (Pt. 2)', 'https://soundcloud.com/user-440517750/the-incomparable-and-unrivaled-lord-jesus-christ-part-2', NULL),
  ('revelation', NULL, 'Revelation 1:9–18', 'The Incomparable and Unrivaled Lord Jesus (Pt. 3)', 'https://soundcloud.com/user-440517750/the-incomparable-and-unrivaled-lord-jesus-christ-part-3', NULL),
  ('revelation', NULL, 'Revelation 1:1–8', 'The Incomparable and Unrivaled Lord Jesus', 'https://soundcloud.com/user-440517750/the-incomparable-and-unrivaled-lord-jesus-christ', NULL),
  ('revelation', NULL, 'Revelation 2:1–7', 'Love or Die', 'https://soundcloud.com/user-440517750/love-or-die', NULL),
  ('revelation', NULL, 'Revelation 2:8–11', 'The Bride that Suffers for Her Groom', 'https://soundcloud.com/user-440517750/the-bride-that-suffers-for-her-groom', NULL),
  ('revelation', NULL, 'Revelation 2:12–17', 'Our Savior is Worthy of a Non-Compromising Church', 'https://soundcloud.com/user-440517750/our-savior-is-worthy-of-a-non-compromising-church', NULL),
  ('revelation', NULL, 'Revelation 2:18–29', 'The Church that Loves Christ and Repents of Sin', 'https://soundcloud.com/user-440517750/the-church-that-loves-christ-and-repents-of-sin', NULL),
  ('revelation', NULL, 'Revelation 3:1–6', 'The Breath of Life in the Church', 'https://soundcloud.com/user-440517750/the-breath-of-life-in-the-church', NULL),
  ('revelation', NULL, 'Revelation 3:7–13', 'The Faithful Church that Clings to Christ and His Promises', 'https://soundcloud.com/user-440517750/the-faithful-church-that-clings-to-christ-and-his-promises', NULL),
  ('revelation', NULL, 'Revelation 3:14–22', 'The Church Without Christ', 'https://soundcloud.com/user-440517750/the-church-without-christ', NULL),
  ('revelation', NULL, 'Revelation 2–3', 'Jesus Christ, the Head of the Church', 'https://soundcloud.com/user-440517750/jesus-christ-the-head-of-the-church', NULL),
  ('revelation', NULL, 'Revelation 5', 'Missions and the Praise and Worship of Christ', 'https://soundcloud.com/user-440517750/missions-and-the-praise-and-worship-of-christ', NULL),
  ('revelation', NULL, 'Revelation 5', 'The Long War Against God''s Missional Plan', 'https://soundcloud.com/user-440517750/the-long-war-against-gods-missional-plan', NULL),
  ('revelation', NULL, 'Revelation 5', 'God''s Unstoppable Missional Plan', 'https://www.youtube.com/live/8_RnDTzk_-s?si=AZ7kkLlt0xrAhbiF', NULL),
  ('revelation', NULL, 'Revelation 19', 'The Beauty of the Bride', 'https://soundcloud.com/user-440517750/the-beauty-of-the-bride', NULL),
  ('romans', NULL, 'Romans 3:10–31', 'Salvation in Christ Alone, through Faith Alone, by Grace Alone', 'https://www.youtube.com/watch?v=X7x7v3QW-1s', NULL),
  ('romans', NULL, 'Romans 6:1–7', 'Identified in Christ: A Follow Up to Baptism', 'https://soundcloud.com/user-440517750/identified-in-christ-a-follow-up-to-todays-baptism', NULL),
  ('romans', NULL, 'Romans 6:17–23', 'God''s Deep Love for the Church, Pt. 3', 'https://youtu.be/jbTCh08Cp4U?si=BsTDXf29GwsROZEm', NULL),
  ('romans', NULL, 'Romans 12:1–5', 'Loving God''s People', 'https://youtu.be/Z1JAVtmg5tA?si=wNpQP8i45qjVwlrX&t=2054', NULL),
  ('romans', NULL, 'Romans 12:1–5', 'The Mercy of God that Unites the Church', 'https://youtu.be/RcTru8F6qdc?si=5HPacxn4rLr1Q78g', NULL),
  ('romans', NULL, 'Romans 12:9–21', 'History, Justice, and Following the Suffering Servant', 'https://soundcloud.com/user-440517750/history-justice-and-following-the-suffering-servant', NULL),
  ('romans', NULL, 'Romans 13:1', 'A Christian''s Response to God and Government', 'https://soundcloud.com/user-440517750/a-christians-response-to-god-and-government', NULL),
  ('romans', NULL, 'Romans 13:1–7', 'Godly Citizenship', 'https://soundcloud.com/user-440517750/godly-citizenship', NULL),
  ('titus', NULL, 'Titus 2:3–5', 'God''s Design for Biblical Womanhood', 'https://youtu.be/zOmRh4CpDtc', NULL),
  ('titus', NULL, 'Titus 2:11–15', 'The Empowering Grace and Glory of Christ in the Present Age', 'https://soundcloud.com/user-440517750/the-empowering-grace-and-glory-of-christ-in-the-present-age', NULL),
  ('titus', NULL, 'Titus 3:1–8', 'The True Follower of Christ', 'https://www.youtube.com/watch?v=w9qkHbI9Iqg', NULL),
  ('titus', NULL, 'Titus 3:3–7', 'Remembering God''s Power to Save Sinners', 'https://youtu.be/ZGjU79fWfl4?si=_BGfgazUkpnjCfaW', NULL),
  ('various', NULL, '', 'Fashioned by God', 'https://soundcloud.com/user-440517750/fashioned-by-god', NULL);
